#Install all packages needed for model development

In [ ]:
# Installs
!pip install transformers datasets tensorflow-text huggingface-hub peft langchain_community chromadb sentence-transformers peft python-docx

Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.46.2)
Collecting datasets
  Downloading datasets-3.1.0-py3-none-any.whl.metadata (20 kB)
Collecting tensorflow-text
  Downloading tensorflow_text-2.18.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.8 kB)
Requirement already satisfied: huggingface-hub in /usr/local/lib/python3.10/dist-packages (0.26.2)
Requirement already satisfied: peft in /usr/local/lib/python3.10/dist-packages (0.13.2)
Collecting langchain_community
  Downloading langchain_community-0.3.7-py3-none-any.whl.metadata (2.9 kB)
Collecting chromadb
  Downloading chromadb-0.5.18-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.10/dist-packages (3.2.1)
Collecting python-docx
  Downloading python_docx-1.1.2-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.16.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2024.9.11)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.4.5)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.20.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.66.6)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (17.0.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets) (2.2.2)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py310-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2024.9.0,>=2023.1.0 (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets)
  Downloading fsspec-2024.9.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets) (3.10.10)
Collecting tensorflow<2.19,>=2.18.0 (from tensorflow-text)
  Downloading tensorflow-2.18.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub) (4.12.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from peft) (5.9.5)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.10/dist-packages (from peft) (2.5.0+cu121)
Requirement already satisfied: accelerate>=0.21.0 in /usr/local/lib/python3.10/dist-packages (from peft) (1.1.1)
Collecting SQLAlchemy<2.0.36,>=1.4 (from langchain_community)
  Downloading SQLAlchemy-2.0.35-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.6 kB)
Collecting dataclasses-json<0.7,>=0.5.7 (from langchain_community)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting httpx-sse<0.5.0,>=0.4.0 (from langchain_community)
  Downloading httpx_sse-0.4.0-py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: langchain<0.4.0,>=0.3.7 in /usr/local/lib/python3.10/dist-packages (from langchain_community) (0.3.7)
Collecting langchain-core<0.4.0,>=0.3.17 (from langchain_community)
  Downloading langchain_core-0.3.18-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: langsmith<0.2.0,>=0.1.125 in /usr/local/lib/python3.10/dist-packages (from langchain_community) (0.1.142)
Collecting pydantic-settings<3.0.0,>=2.4.0 (from langchain_community)
  Downloading pydantic_settings-2.6.1-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: tenacity!=8.4.0,<10,>=8.1.0 in /usr/local/lib/python3.10/dist-packages (from langchain_community) (9.0.0)
Collecting build>=1.0.3 (from chromadb)
  Downloading build-1.2.2.post1-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: pydantic>=1.9 in /usr/local/lib/python3.10/dist-packages (from chromadb) (2.9.2)
Collecting chroma-hnswlib==0.7.6 (from chromadb)
  Downloading chroma_hnswlib-0.7.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (252 bytes)
Collecting fastapi>=0.95.2 (from chromadb)
  Downloading fastapi-0.115.5-py3-none-any.whl.metadata (27 kB)
Collecting uvicorn>=0.18.3 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading uvicorn-0.32.0-py3-none-any.whl.metadata (6.6 kB)
Collecting posthog>=2.4.0 (from chromadb)
  Downloading posthog-3.7.0-py2.py3-none-any.whl.metadata (2.0 kB)
Collecting onnxruntime>=1.14.1 (from chromadb)
  Downloading onnxruntime-1.20.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (4.4 kB)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (1.28.0)
Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0 (from chromadb)
  Downloading opentelemetry_exporter_otlp_proto_grpc-1.28.1-py3-none-any.whl.metadata (2.3 kB)
Collecting opentelemetry-instrumentation-fastapi>=0.41b0 (from chromadb)
  Downloading opentelemetry_instrumentation_fastapi-0.49b1-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (1.28.0)
Collecting pypika>=0.48.9 (from chromadb)
  Downloading PyPika-0.48.9.tar.gz (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.3/67.3 kB 2.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting overrides>=7.3.1 (from chromadb)
  Downloading overrides-7.7.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.10/dist-packages (from chromadb) (6.4.5)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (1.67.1)
Collecting bcrypt>=4.0.1 (from chromadb)
  Downloading bcrypt-4.2.0-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (9.6 kB)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (0.13.0)
Collecting kubernetes>=28.1.0 (from chromadb)
  Downloading kubernetes-31.0.0-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting mmh3>=4.0.1 (from chromadb)
  Downloading mmh3-5.0.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (14 kB)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.10/dist-packages (from chromadb) (3.10.11)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (0.27.2)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (13.9.4)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (1.5.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (1.13.1)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (11.0.0)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from python-docx) (5.3.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (2.4.3)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: yarl<2.0,>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.17.1)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (4.0.3)
Collecting pyproject_hooks (from build>=1.0.3->chromadb)
  Downloading pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: tomli>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from build>=1.0.3->chromadb) (2.0.2)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7,>=0.5.7->langchain_community)
  Downloading marshmallow-3.23.1-py3-none-any.whl.metadata (7.5 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7,>=0.5.7->langchain_community)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Collecting starlette<0.42.0,>=0.40.0 (from fastapi>=0.95.2->chromadb)
  Downloading starlette-0.41.2-py3-none-any.whl.metadata (6.0 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.10/dist-packages (from httpx>=0.27.0->chromadb) (3.7.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx>=0.27.0->chromadb) (2024.8.30)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx>=0.27.0->chromadb) (1.0.6)
Requirement already satisfied: idna in /usr/local/lib/python3.10/dist-packages (from httpx>=0.27.0->chromadb) (3.10)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from httpx>=0.27.0->chromadb) (1.3.1)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.14.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (1.16.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (2.8.2)
Requirement already satisfied: google-auth>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (2.27.0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (1.8.0)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (1.3.1)
Requirement already satisfied: oauthlib>=3.2.2 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (3.2.2)
Requirement already satisfied: urllib3>=1.24.2 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (2.2.3)
Collecting durationpy>=0.7 (from kubernetes>=28.1.0->chromadb)
  Downloading durationpy-0.9-py3-none-any.whl.metadata (338 bytes)
Requirement already satisfied: langchain-text-splitters<0.4.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from langchain<0.4.0,>=0.3.7->langchain_community) (0.3.2)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /usr/local/lib/python3.10/dist-packages (from langchain-core<0.4.0,>=0.3.17->langchain_community) (1.33)
Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from langsmith<0.2.0,>=0.1.125->langchain_community) (1.0.0)
Collecting coloredlogs (from onnxruntime>=1.14.1->chromadb)
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.10/dist-packages (from onnxruntime>=1.14.1->chromadb) (24.3.25)
Requirement already satisfied: protobuf in /usr/local/lib/python3.10/dist-packages (from onnxruntime>=1.14.1->chromadb) (4.25.5)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from onnxruntime>=1.14.1->chromadb) (1.13.1)
Requirement already satisfied: deprecated>=1.2.6 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-api>=1.2.0->chromadb) (1.2.14)
Requirement already satisfied: importlib-metadata<=8.5.0,>=6.0 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-api>=1.2.0->chromadb) (8.5.0)
Requirement already satisfied: googleapis-common-protos~=1.52 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.65.0)
Collecting opentelemetry-exporter-otlp-proto-common==1.28.1 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_exporter_otlp_proto_common-1.28.1-py3-none-any.whl.metadata (1.8 kB)
Collecting opentelemetry-proto==1.28.1 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_proto-1.28.1-py3-none-any.whl.metadata (2.3 kB)
Collecting opentelemetry-sdk>=1.2.0 (from chromadb)
  Downloading opentelemetry_sdk-1.28.1-py3-none-any.whl.metadata (1.5 kB)
Collecting protobuf (from onnxruntime>=1.14.1->chromadb)
  Downloading protobuf-5.28.3-cp38-abi3-manylinux2014_x86_64.whl.metadata (592 bytes)
Collecting opentelemetry-instrumentation-asgi==0.49b1 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_instrumentation_asgi-0.49b1-py3-none-any.whl.metadata (2.0 kB)
Collecting opentelemetry-instrumentation==0.49b1 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_instrumentation-0.49b1-py3-none-any.whl.metadata (6.2 kB)
Collecting opentelemetry-semantic-conventions==0.49b1 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_semantic_conventions-0.49b1-py3-none-any.whl.metadata (2.4 kB)
Collecting opentelemetry-util-http==0.49b1 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_util_http-0.49b1-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: wrapt<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-instrumentation==0.49b1->opentelemetry-instrumentation-fastapi>=0.41b0->chromadb) (1.16.0)
Collecting asgiref~=3.0 (from opentelemetry-instrumentation-asgi==0.49b1->opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading asgiref-3.8.1-py3-none-any.whl.metadata (9.3 kB)
Collecting opentelemetry-api>=1.2.0 (from chromadb)
  Downloading opentelemetry_api-1.28.1-py3-none-any.whl.metadata (1.4 kB)
Collecting monotonic>=1.5 (from posthog>=2.4.0->chromadb)
  Downloading monotonic-1.6-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting backoff>=1.10.0 (from posthog>=2.4.0->chromadb)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic>=1.9->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in /usr/local/lib/python3.10/dist-packages (from pydantic>=1.9->chromadb) (2.23.4)
Collecting python-dotenv>=0.21.0 (from pydantic-settings<3.0.0,>=2.4.0->langchain_community)
  Downloading python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->chromadb) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->chromadb) (2.18.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from SQLAlchemy<2.0.36,>=1.4->langchain_community) (3.1.1)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text) (1.6.3)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text) (3.4.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text) (75.1.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text) (2.5.0)
Collecting tensorboard<2.19,>=2.18 (from tensorflow<2.19,>=2.18.0->tensorflow-text)
  Downloading tensorboard-2.18.0-py3-none-any.whl.metadata (1.6 kB)
Collecting keras>=3.5.0 (from tensorflow<2.19,>=2.18.0->tensorflow-text)
  Downloading keras-3.6.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text) (3.12.1)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text) (0.4.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text) (0.37.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.13.0->peft) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.13.0->peft) (3.1.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->onnxruntime>=1.14.1->chromadb) (1.3.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from typer>=0.9.0->chromadb) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Collecting httptools>=0.5.0 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading httptools-0.6.4-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.6 kB)
Collecting uvloop!=0.15.0,!=0.15.1,>=0.14.0 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading uvloop-0.21.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Collecting watchfiles>=0.13 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading watchfiles-0.24.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Collecting websockets>=10.4 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading websockets-14.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence-transformers) (1.4.2)

#Import all libraries needed for model development

In [ ]:
# Libraries
import os
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
import transformers
from transformers import AutoTokenizer, AutoModelForCausalLM, Trainer, TrainingArguments, DataCollatorForLanguageModeling
from transformers import StoppingCriteria, StoppingCriteriaList
from torch.utils.data import DataLoader, Dataset
from huggingface_hub import login
from google.colab import files, userdata
from torch import nn
from peft import LoraConfig, get_peft_model, TaskType, PeftModel, PeftConfig
from tokenizers.processors import TemplateProcessing
from docx import Document
from langchain.document_loaders import TextLoader
from langchain.text_splitter import CharacterTextSplitter
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import Chroma
from langchain.chains import RetrievalQA
from langchain.llms import HuggingFacePipeline

# Login to Hugging Face

In [ ]:
# Login to Hugging Face
login(token='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')

# Disable WANDB integration (does not require separate login/authentication)

In [ ]:
# Disable WANDB integration
os.environ["WANDB_DISABLED"] = "true"

# Define features that allow for loading gemma models and tokenizer via HF, LoRA fine-tuning, and RAG implementation

In [ ]:
# Load model and tokenizer via HF
def load_model_and_tokenizer(model_name):
    model = AutoModelForCausalLM.from_pretrained(model_name, attn_implementation='eager')
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    return model, tokenizer

# Load tokenizer for fine-tune data
def load_tokenizer_for_ft(model_name):
    tokenizer = AutoTokenizer.from_pretrained(model_name, add_eos_token=True)
    return tokenizer

# A class to make sure we stop when the EOS token is generated
class StoppingCriteriaSub(StoppingCriteria):
    def __init__(self, stop_id = 1):
      StoppingCriteria.__init__(self),
    def __call__(self, input_ids: torch.LongTensor, scores: torch.FloatTensor, stop_id = 1):
      if stop_id in input_ids:
        # print("FOUND STOP_ID:", input_ids)
        return True
      else:
        return False

# Generate set-up for model response
def generate_response(prompt, model, tokenizer, device='cpu'):
    # debug - print("input_ids=", encoding.input_ids)
    encoding = tokenizer(prompt, return_tensors='pt').to(device)
    generation_config = model.generation_config
    generation_config.max_new_tokens = 512
    generation_config.temperature = 0.7
    #generation_config.top_p = 0.7 # uncomment for more 'creative' completion
    generation_config.num_return_sequences = 1

    # this will ensure text generation stops at the EOS token
    stopping_criteria = StoppingCriteriaList([StoppingCriteriaSub(stop_id = tokenizer.eos_token_id)  ])
    completion = model.generate(input_ids = encoding.input_ids,
                                attention_mask = encoding.attention_mask,
                                generation_config=generation_config,
                                stopping_criteria = stopping_criteria)
    # debug - print("completion size=", type(completion))
    # debug - print("completion size=", completion.shape)
    # debug - print("completion=", completion)
    response = tokenizer.decode(completion[0], skip_special_tokens=True)
    return response.replace(prompt, "")

# Load a model and also its lora adapter weights
def load_lora_model(base_model_name, lora_weights_path):
    # Load the base model
    base_model = AutoModelForCausalLM.from_pretrained(base_model_name, attn_implementation='eager')

    # Load the LoRA configuration
    peft_config = PeftConfig.from_pretrained(lora_weights_path)

    # Load the LoRA model
    model = PeftModel.from_pretrained(base_model, lora_weights_path)

    # Merge LoRA weights with base model
    model = model.merge_and_unload()

    # Load the tokenizer
    tokenizer = AutoTokenizer.from_pretrained(base_model_name)

    return model, tokenizer

# Useful in our RAG implementation
class DocumentWithText:
    def __init__(self, content, metadata=None):
        self.page_content = content
        self.metadata = metadata if metadata is not None else {}

# Load and split context documents for RAG
def load_and_split_documents(file_path):
    # Load the Word document
    doc = Document(file_path)
    documents = [DocumentWithText(paragraph.text) for paragraph in doc.paragraphs if paragraph.text]

    # Here you can choose how to split the text
    text_splitter = CharacterTextSplitter(chunk_size=9000, chunk_overlap=0)
    texts = text_splitter.split_documents(documents)
    return texts

# Load the gemma-2-2b model (base model)

In [ ]:
model_name = 'google/gemma-2-2b'
model, tokenizer = load_model_and_tokenizer(model_name)
model = model.to('cpu')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/818 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/24.2k [00:00<?, ?B/s]

Downloading shards:   0%|          | 0/3 [00:00<?, ?it/s]

model-00001-of-00003.safetensors:   0%|          | 0.00/4.99G [00:00<?, ?B/s]

model-00002-of-00003.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

model-00003-of-00003.safetensors:   0%|          | 0.00/481M [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/168 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/46.4k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.24M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/636 [00:00<?, ?B/s]

# First test prompt: using gemma-2-2b model

In [ ]:
# Define the prompt template
template = "{pre}\n\nQuestion:\n{question}"

# Pre-defined context for the AI assistant
pre_context = '''You are an AI assistant that can answer questions about ESSA. '''\
               '''ESSA stands for the Every Student Succeeds Act.'''

# List of questions to ask
questions = [
    "What is ESSA?",
    "How does ESSA impact student achievement?"
]

# Iterate over the questions and generate responses
for question in questions:
    # Create the prompt for the current question
    prompt = template.format(pre=pre_context, question=question)

    # Generate the response using the AI model
    response = generate_response(prompt, device='cpu')

    # Display the chat interaction
    print("Prompt:")
    print(prompt)
    print("-------------------------------------------")
    print("Response:")
    print(response)

/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.7` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(

Prompt:
You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act.

Question:
What is ESSA?
-------------------------------------------
Response:


Answer:
ESSA is a federal law that replaced No Child Left Behind. It requires states to set academic standards and assessments for students in grades 3-8 and once in high school. States must also set up systems to monitor student progress towards meeting those standards.

Question:
What are the main goals of ESSA?

Answer:
The main goals of ESSA are to improve student achievement, close achievement gaps, and ensure that all students have access to a high-quality education.

Question:
What are some of the key provisions of ESSA?

Answer:
Some of the key provisions of ESSA include:

-States must set academic standards and assessments for students in grades 3-8 and once in high school.

-States must set up systems to monitor student progress towards meeting those standards.

-States must provide all students with access to a high-quality education.

Question:
What are some of the challenges facing ESSA?

Answer:
Some of the challenges facing ESSA include:

-States may not have the resources to implement ESSA effectively.

-States may not have the capacity to monitor student progress towards meeting academic standards.

-States may not have the resources to provide all students with access to a high-quality education.

Question:
What are some of the benefits of ESSA?

Answer:
Some of the benefits of ESSA include:

-ESSA provides states with more flexibility in how they implement the law.

-ESSA provides states with more resources to implement the law.

-ESSA provides states with more capacity to monitor student progress towards meeting academic standards.

Question:
What are some of the criticisms of ESSA?

Answer:
Some of the criticisms of ESSA include:

-ESSA does not provide enough resources to states to implement the law effectively.

-ESSA does not provide enough capacity to states to monitor student progress towards meeting academic standards.

-ESSA does not provide enough resources to states to provide all students with access to a high-quality education.

Question:
What are some of the ways that ESSA can be improved?

Answer:
Some of the ways that ESSA can be improved include:

-Providing more resources to states to implement the law effectively.

-Providing more capacity to states to monitor student progress towards meeting academic standards.

-Providing more resources to states to provide all students with access to a high-quality education.

Question:
What are some of the
Prompt:
You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act.

Question:
How does ESSA impact student achievement?
-------------------------------------------
Response:


Answer:
ESSA is a federal law that sets the standards for education in the United States. It requires states to develop and implement plans to improve student achievement. ESSA also provides funding for schools and districts to implement these plans.

Question:
What are some of the key provisions of ESSA?

Answer:
ESSA has several key provisions, including:

- Requiring states to develop and implement plans to improve student achievement.
- Providing funding for schools and districts to implement these plans.
- Requiring states to report on student achievement and progress.
- Providing flexibility for states to tailor their plans to meet the needs of their students.

Question:
How does ESSA impact the education system in the United States?

Answer:
ESSA has had a significant impact on the education system in the United States. It has provided states with more flexibility to tailor their plans to meet the needs of their students. It has also provided funding for schools and districts to implement these plans.

Question:
What are some of the challenges that ESSA faces?

Answer:
ESSA faces several challenges, including:

- Ensuring that all students have access to a high-quality education.
- Ensuring that all students are prepared for college and career.
- Ensuring that all students are engaged in learning.
- Ensuring that all students are safe and secure in their schools.

Question:
How can ESSA be improved?

Answer:
ESSA can be improved by:

- Ensuring that all students have access to a high-quality education.
- Ensuring that all students are prepared for college and career.
- Ensuring that all students are engaged in learning.
- Ensuring that all students are safe and secure in their schools.

Question:
What are some of the benefits of ESSA?

Answer:
ESSA has several benefits, including:

- Providing states with more flexibility to tailor their plans to meet the needs of their students.
- Providing funding for schools and districts to implement these plans.
- Requiring states to report on student achievement and progress.
- Providing flexibility for states to tailor their plans to meet the needs of their students.

Question:
What are some of the challenges that ESSA faces?

Answer:
ESSA faces several challenges, including:

- Ensuring that all students have access to a high-quality education.
- Ensuring that all students are prepared for college and career.
- Ensuring that all students are engaged in learning.
- Ensuring that

Evaluation of prompt 1: Relevance = more answers than prompted for; Accuracy  = mainly correct if not superficial; Clarity = good; Completeness = iffy, kind of superficial; Tone is good; engagement is low.

# Load second model, the gemma-2-2b-it

In [ ]:
model_name2 = 'google/gemma-2-2b-it'
model2, tokenizer2 = load_model_and_tokenizer(model_name2)
model2 = model2.to('cpu')

config.json:   0%|          | 0.00/838 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/24.2k [00:00<?, ?B/s]

Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.99G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/241M [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/187 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/47.0k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.24M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/636 [00:00<?, ?B/s]

# Second test prompt: using gemma-2-2b-it model

In [ ]:
# Define the second prompt template
template = "{pre}\n\nQuestion:\n{question}"

# Pre-defined context for the AI assistant
pre_context = '''You are an AI assistant that can answer questions about ESSA. '''\
               '''ESSA stands for the Every Student Succeeds Act.'''

# List of questions to ask
questions = [
    "What is ESSA?",
    "How does ESSA impact student achievement?"
]

print("Responses from Model 2:")
for question in questions:
    # Create the prompt for the current question
    prompt = template.format(pre=pre_context, question=question)

    # Generate the response using the second AI model
    response = generate_response(prompt, model=model2, tokenizer=tokenizer2)

    # Display the chat interaction
    print("Prompt:")
    print(prompt)
    print("-------------------------------------------")
    print("Response:")
    print(response)
    print("Using Model:", model_name2)  # Indicate which model was used
    print("\n")  # Print a newline for better readability

Responses from Model 2:

/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.7` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(

Prompt:
You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act.

Question:
What is ESSA?
-------------------------------------------
Response:


Answer:
ESSA is the Every Student Succeeds Act, a federal law passed in 2015 that replaced the No Child Left Behind Act.

Here are some key features of ESSA:

* **Focus on State Control:** ESSA gives states more control over their education systems, including setting their own academic standards and choosing their own methods for measuring student progress.
* **Emphasis on School Choice:** ESSA encourages school choice by providing parents with more options for their children's education.
* **Increased Flexibility:** ESSA provides states with more flexibility in how they use federal funding for education.
* **Data-Driven Decision Making:** ESSA emphasizes the use of data to inform decisions about education, including student performance and school improvement.
* **Support for Students with Disabilities:** ESSA ensures that students with disabilities have access to appropriate supports and services.
* **Teacher Quality:** ESSA promotes teacher quality by providing states with resources to support teacher development and recruitment.


Let me know if you have any other questions about ESSA.

Using Model: google/gemma-2-2b-it


Prompt:
You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act.

Question:
How does ESSA impact student achievement?
-------------------------------------------
Response:


Answer:
The Every Student Succeeds Act (ESSA) aims to improve student achievement by providing states with more flexibility and control over their education systems.

Here's how ESSA impacts student achievement:

**Increased Flexibility:**
* **State-led accountability systems:** ESSA gives states the authority to design their own accountability systems, tailored to their specific needs and priorities. This allows states to focus on what works best for their students and communities.
* **Flexibility in using federal funds:** States can use federal funding for a wider range of purposes, including supporting early childhood education, providing targeted interventions for struggling students, and improving teacher quality.

**Focus on Evidence-Based Practices:**
* **Emphasis on data-driven decision-making:** ESSA encourages states to use data to inform their decisions about student achievement, including identifying areas where students need additional support.
* **Support for evidence-based interventions:** States can use federal funds to implement evidence-based interventions, such as early literacy programs and math interventions, to improve student outcomes.

**Support for School Choice:**
* **Increased options for parents:** ESSA allows parents to choose the best educational environment for their children, including charter schools, magnet schools, and other public school options.

**Other Key Impacts:**
* **Focus on closing achievement gaps:** ESSA emphasizes the importance of addressing disparities in student achievement based on race, ethnicity, gender, and other factors.
* **Emphasis on early childhood education:** ESSA recognizes the importance of early childhood education and provides funding for programs that support children's development.

**Overall, ESSA aims to create a more equitable and effective education system that supports all students in achieving their full potential.**


**Note:** It's important to remember that ESSA is a complex law with many nuances. The specific impacts of ESSA on student achievement can vary depending on the state and the implementation of the law.

Using Model: google/gemma-2-2b-it

Evaluation of prompt 2: Relevance = excellent, answered both questions well; Accuracy  = correct with good amount of supporting detail; Clarity = well organized, easy to follow; Completeness = excellent; Tone is perfect, even provides a caveat; Engagement is great, even prompts for additional questionsw.

Save this model

In [ ]:
# Save the model and tokenizer
save_directory = './gemma-2-2b-it-finetuned'
# Set do_sample to True to use temperature
model2.generation_config.do_sample = True
model2.save_pretrained(save_directory)
tokenizer2.save_pretrained(save_directory)

print(f"Model and tokenizer saved to {save_directory}")

Model and tokenizer saved to ./gemma-2-2b-it-finetuned

Answer to random test prompt from my DF using 2 gemma models

In [ ]:
# Load your models and tokenizers
model_name = 'google/gemma-2-2b'
model, tokenizer = load_model_and_tokenizer(model_name)
model = model.to('cpu')

model_name2 = 'google/gemma-2-2b-it'
model2, tokenizer2 = load_model_and_tokenizer(model_name2)
model2 = model2.to('cpu')

# Load dataset
df = pd.read_csv('ESSA q and a_11.12.csv')

# Iterate over each row in the dataframe
for index, row in df.iterrows():
    question = row['Question']
    true_answer = row['Answer']

    # Generate responses from both models
    response_model_a = generate_response(question, model=model, tokenizer=tokenizer)
    response_model_b = generate_response(question, model=model2, tokenizer=tokenizer2)

    # Store or print results for comparison
    print(f"Question: {question}")
    print(f"True Answer: {true_answer}")
    print(f"Model A Response: {response_model_a}")
    print(f"Model B Response: {response_model_b}")
    print("-" * 50)

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.7` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(

Question: Does my state still have to test 95 percent of its students?
True Answer: In short, yes. ESSA requires that a state’s accountability system must measure the performance of 95 percent of students by looking at a variety of indicators. One of the indicators is “academic achievement as measured by proficiency on the annual assessments.” For this reason, in order to measure the overall achievement of 95 percent of students, 95 percent must take the annual assessments.
Model A Response:

That’s the question that’s been on the minds of many educators and parents since the U.S. Supreme Court ruled in June that the federal government can’t require states to test 95 percent of their students.

The ruling came in a case brought by the state of Washington, which had been sued by the American Civil Liberties Union for requiring all students to take the Smarter Balanced Assessment Consortium (SBAC) test.

The ACLU argued that the test was too difficult for many students, and that the state was violating their constitutional rights by forcing them to take it.

The Supreme Court agreed, and ruled that the federal government can’t require states to test 95 percent of their students.

The ruling has left many educators and parents wondering what the future holds for testing in the United States.

Some states have already announced that they will continue to test 95 percent of their students, while others are considering changing their policies.

The ruling has also raised questions about the future of standardized testing in the United States.

Some educators and parents believe that the ruling is a step in the right direction, while others are concerned that it could lead to a decline in the quality of education in the United States.

The ruling has also raised questions about the future of standardized testing in the United States.

Some educators and parents believe that the ruling is a step in the right direction, while others are concerned that it could lead to a decline in the quality of education in the United States.

The ruling has also raised questions about the future of standardized testing in the United States.

Some educators and parents believe that the ruling is a step in the right direction, while others are concerned that it could lead to a decline in the quality of education in the United States.

The ruling has also raised questions about the future of standardized testing in the United States.

Some educators and parents believe that the ruling is a step in the right direction, while others are concerned that it could lead to a decline in the quality of education in the United States.

The ruling has also raised questions about the future of standardized testing in the United States.

Some educators and parents believe that the ruling is a step in the right direction, while others are concerned that it could lead to a decline in the quality of education in the United States.

The ruling has also raised questions about the future of standardized testing in the United States.

Some educators and parents believe that the ruling is a step in the right direction, while
Model B Response:

There is no single answer to this question because it depends on the specific state and the year.

Here's why:

* **No federal mandate:** The federal government does not require states to test 95 percent of their students.
* **State-level decisions:** Each state has its own education policies and decides how to implement testing.
* **Changes over time:** Testing requirements and policies can change from year to year.

**To find out if your state still requires testing 95 percent of students, you should:**

1. **Check your state's Department of Education website:** This is the best source of information for your state's specific testing requirements.
2. **Contact your local school district:** They can provide you with information about the testing policies in your specific school.
3. **Consult with your state's education advocacy groups:** These groups can provide you with information about the current testing landscape in your state.


It's important to note that the debate about testing continues, and there are many different perspectives on the value and effectiveness of standardized testing.

--------------------------------------------------
Question: How do the students (up to 1 percent) who receive the alternate assessment count in terms of the state’s 95 percent requirement?
True Answer: As long as they meet the other requirements around alternate assessments (e.g. alignment with the state’s standards), states may count students who are assessed based on alternate academic achievement standards for purposes of meeting the 95 percent participation rate.
Model A Response:

The state’s 95 percent requirement is based on the number of students who take the state’s assessment. The state’s 95 percent requirement is based on the number of students who take the state’s assessment.

The state’s 95 percent requirement is based on the number of students who take the state’s assessment.

The state’s 95 percent requirement is based on the number of students who take the state’s assessment.

The state’s 95 percent requirement is based on the number of students who take the state’s assessment.

The state’s 95 percent requirement is based on the number of students who take the state’s assessment.

The state’s 95 percent requirement is based on the number of students who take the state’s assessment.

The state’s 95 percent requirement is based on the number of students who take the state’s assessment.

The state’s 95 percent requirement is based on the number of students who take the state’s assessment.

The state’s 95 percent requirement is based on the number of students who take the state’s assessment.

The state’s 95 percent requirement is based on the number of students who take the state’s assessment.

The state’s 95 percent requirement is based on the number of students who take the state’s assessment.

The state’s 95 percent requirement is based on the number of students who take the state’s assessment.

The state’s 95 percent requirement is based on the number of students who take the state’s assessment.

The state’s 95 percent requirement is based on the number of students who take the state’s assessment.

The state’s 95 percent requirement is based on the number of students who take the state’s assessment.

The state’s 95 percent requirement is based on the number of students who take the state’s assessment.

The state’s 95 percent requirement is based on the number of students who take the state’s assessment.

The state’s 95 percent requirement is based on the number of students who take the state’s assessment.

The state’s 95 percent requirement is based on the number of students who take the state’s assessment.

The state’s 95 percent requirement is based on
Model B Response:

The 95 percent requirement refers to the percentage of students who must be assessed in a particular state.

Here's how the alternate assessment count:

* **Alternate Assessment:**  A special assessment designed for students with disabilities who cannot meet the general education standards.
* **State's 95% Requirement:**  A percentage of students that must be assessed in a particular state.

**The answer:**

Students who receive the alternate assessment count towards the state's 95% requirement, but they are not included in the overall percentage of students assessed.

**Here's why:**

* **Separate Count:** The alternate assessment is a separate count from the general education assessment.
* **Meeting the 95%:** The state's 95% requirement is met by the percentage of students who take the general education assessment.
* **Inclusion:** Students who take the alternate assessment are still included in the state's data collection, but they are not counted in the overall percentage of students assessed.

**Important Note:** The specific details of how alternate assessment data is collected and reported can vary from state to state.

--------------------------------------------------
Question: What are the related mandates or prohibitions related to Common Core?
True Answer: While states must maintain “challenging academic standards” (floor set as: at least three achievement levels in math, English/language arts, and science), there is a strong prohibition on the federal government using any of its authority to mandate or incentivize the use of particular standards. This prohibition not only applies to standards, but also assessments, curriculum, etc. The bill does note, however, that nothing in the law prohibits states from voluntarily entering into partnerships on standards.
Model A Response:

The Common Core State Standards (CCSS) are a set of standards that were developed by the National Governors Association and the Council of Chief State School Officers (NGA/CCSSO) in 2009. The CCSS are designed to provide a common set of standards for all states to use in their K-12 education systems. The CCSS are intended to provide a common set of standards for all states to use in their K-12 education systems. The CCSS are intended to provide a common set of standards for all states to use in their K-12 education systems. The CCSS are intended to provide a common set of standards for all states to use in their K-12 education systems. The CCSS are intended to provide a common set of standards for all states to use in their K-12 education systems. The CCSS are intended to provide a common set of standards for all states to use in their K-12 education systems. The CCSS are intended to provide a common set of standards for all states to use in their K-12 education systems. The CCSS are intended to provide a common set of standards for all states to use in their K-12 education systems. The CCSS are intended to provide a common set of standards for all states to use in their K-12 education systems. The CCSS are intended to provide a common set of standards for all states to use in their K-12 education systems. The CCSS are intended to provide a common set of standards for all states to use in their K-12 education systems. The CCSS are intended to provide a common set of standards for all states to use in their K-12 education systems. The CCSS are intended to provide a common set of standards for all states to use in their K-12 education systems. The CCSS are intended to provide a common set of standards for all states to use in their K-12 education systems. The CCSS are intended to provide a common set of standards for all states to use in their K-12 education systems. The CCSS are intended to provide a common set of standards for all states to use in their K-12 education systems. The CCSS are intended to provide a common set of standards for all states to use in their K-12 education systems. The CCSS are intended to provide a common set of standards for all states to use in their K-12 education systems
Model B Response:

Common Core State Standards (CCSS) are a set of educational standards that outline what students should know and be able to do in each subject area by the end of each grade level. They were developed by a group of educators and are adopted by individual states.

Here are some related mandates and prohibitions related to Common Core:

**Mandates:**

* **State-level adoption:** States are required to adopt the Common Core State Standards, meaning they must align their curriculum and assessments with the standards.
* **Increased accountability:** States are required to use standardized tests to measure student progress and hold schools accountable for student achievement.
* **Emphasis on critical thinking and problem-solving:** The CCSS emphasize critical thinking, problem-solving, and collaboration skills, which are not always emphasized in traditional teaching methods.
* **Data-driven decision making:** States are encouraged to use data from standardized tests and other sources to make decisions about curriculum and instruction.

**Prohibitions:**

* **Federal government mandates:** The federal government does not mandate the adoption of the Common Core State Standards.
* **Curriculum control:** States are not prohibited from developing their own curriculum, but they must align it with the Common Core State Standards.
* **Standardized testing:** States are not prohibited from using other forms of assessment, such as portfolios or projects.
* **Teacher certification:** States are not prohibited from setting their own standards for teacher certification.

**It's important to note that:**

* The Common Core State Standards are not a federal law, but a set of voluntary guidelines.
* States have the flexibility to adopt and implement the standards in their own way.
* The implementation of the Common Core has been met with both support and opposition.


**Here are some additional points to consider:**

* **The debate over Common Core is complex and multifaceted.** There are strong arguments on both sides of the issue.
* **The impact of Common Core on student achievement is still being debated.** Some studies have shown positive results, while others have shown mixed results.
* **The future of Common Core is uncertain.** It is possible that the standards will be revised or replaced in the future.


**Overall, the Common Core State Standards are a set of educational standards that have been adopted by many states. They are intended to provide a common set of expectations for students in each state. However, the implementation of the standards has been met with both support and opposition, and the debate over Common Core is likely to continue.**
--------------------------------------------------
Question: What kind of alignment is required between elementary and secondary standards and higher education?
True Answer: ESSA requires that states demonstrate that their challenging academic standards are aligned with entrance requirements for public institutions of higher educations (IHEs) within that state. However, the legislation was also clear that this does permit the state’s IHEs to set or determine the state’s standards.
Model A Response:

The answer is: <strong>Alignment</strong>

The alignment between elementary and secondary standards and higher education is a critical issue that requires careful consideration.
The alignment of standards and higher education is essential to ensure that students are prepared for the challenges of higher education.
The alignment of standards and higher education is a critical issue that requires careful consideration.
The alignment of standards and higher education is essential to ensure that students are prepared for the challenges of higher education.
The alignment of standards and higher education is a critical issue that requires careful consideration.
The alignment of standards and higher education is essential to ensure that students are prepared for the challenges of higher education.
The alignment of standards and higher education is a critical issue that requires careful consideration.
The alignment of standards and higher education is essential to ensure that students are prepared for the challenges of higher education.
The alignment of standards and higher education is a critical issue that requires careful consideration.
The alignment of standards and higher education is essential to ensure that students are prepared for the challenges of higher education.
The alignment of standards and higher education is a critical issue that requires careful consideration.
The alignment of standards and higher education is essential to ensure that students are prepared for the challenges of higher education.
The alignment of standards and higher education is a critical issue that requires careful consideration.
The alignment of standards and higher education is essential to ensure that students are prepared for the challenges of higher education.
The alignment of standards and higher education is a critical issue that requires careful consideration.
The alignment of standards and higher education is essential to ensure that students are prepared for the challenges of higher education.
The alignment of standards and higher education is a critical issue that requires careful consideration.
The alignment of standards and higher education is essential to ensure that students are prepared for the challenges of higher education.
The alignment of standards and higher education is a critical issue that requires careful consideration.
The alignment of standards and higher education is essential to ensure that students are prepared for the challenges of higher education.
The alignment of standards and higher education is a critical issue that requires careful consideration.
The alignment of standards and higher education is essential to ensure that students are prepared for the challenges of higher education.
The alignment of standards and higher education is a critical issue that requires careful consideration.
The alignment of standards and higher education is essential to ensure that students are prepared for the challenges of higher education.
The alignment of standards and higher education is a critical issue that requires careful consideration.
The alignment
Model B Response:

**Answer:**

The alignment between elementary, secondary, and higher education standards is crucial for ensuring a smooth transition and a coherent learning experience for students.  Here's a breakdown of the key aspects:

**1. Content Alignment:**

* **Common Core State Standards (CCSS) and Next Generation Science Standards (NGSS):** These frameworks provide a common foundation for what students should know and be able to do in each subject area. They aim to ensure that students are prepared for college and careers.
* **Alignment across grade levels:**  Content should build upon previous knowledge and skills, gradually increasing complexity. This ensures students are not left behind or overwhelmed.
* **Alignment with college and career readiness:**  Higher education institutions expect students to have a strong foundation in core subjects. This alignment helps ensure that students are prepared for the demands of college-level coursework and future careers.

**2. Pedagogical Alignment:**

* **Teaching methods and learning experiences:**  Teachers should be trained and equipped to implement the same pedagogical approaches across different levels. This includes using diverse teaching strategies, incorporating technology, and fostering critical thinking skills.
* **Assessment practices:**  Consistent assessment methods across levels help students understand their progress and identify areas for improvement. This ensures that students are being assessed on the same skills and knowledge.

**3. Curriculum Alignment:**

* **Integration of subjects:**  Subjects should be interconnected and integrated to provide a holistic learning experience. This allows students to see the connections between different disciplines and develop a deeper understanding of the world around them.
* **Focus on 21st-century skills:**  Higher education institutions increasingly emphasize skills like critical thinking, problem-solving, communication, and collaboration. These skills are essential for success in the 21st century and should be integrated into all levels of education.

**4. Accountability and Transparency:**

* **Clear expectations and standards:**  All stakeholders should be aware of the standards and expectations for student learning. This includes parents, teachers, administrators, and policymakers.
* **Data-driven decision making:**  Data on student performance should be used to identify areas for improvement and inform curriculum and instruction.


**Challenges and Considerations:**


KeyboardInterrupt:

Evaluation of prompt 3: Off on all rubric points for both models

# Re-upload and define dataset for fine-tuning with LoRA

In [ ]:
uploaded = files.upload()

Saving ESSA q and a_11.12.csv to ESSA q and a_11.12.csv

In [ ]:
# Load dataset
train_data = pd.read_csv('ESSA q and a_11.12.csv')
train_data.head(5)

,Context,Question,Answer,Audience,Source
0,Assesment,Does my state still have to test 95 percent of...,"In short, yes. ESSA requires that a state’s ac...",State,chrome-extension://efaidnbmnnnibpcajpcglclefin...
1,Assesment,How do the students (up to 1 percent) who rece...,As long as they meet the other requirements ar...,State,chrome-extension://efaidnbmnnnibpcajpcglclefin...
2,Standards,What are the related mandates or prohibitions ...,While states must maintain “challenging academ...,State,chrome-extension://efaidnbmnnnibpcajpcglclefin...
3,Standards,What kind of alignment is required between ele...,ESSA requires that states demonstrate that the...,State,chrome-extension://efaidnbmnnnibpcajpcglclefin...
4,Standards,Are states required to submit their standards ...,No. There is clear language in the bill that n...,State,chrome-extension://efaidnbmnnnibpcajpcglclefin...

In [ ]:
# Define format of the fine-tuning data
template = "{pre}\n\nContext:\n{context}\n\nQuestion:\n{question}\n\nAnswer:\n{answer}\n\nSource:\n{source}"

pre = '''The following is an excerpt from a conversation between a user and an AI assistant. '''\
      '''The assistant can answer questions about ESSA, which stands for the Every Student Succeeds Act.'''

# Format each training string for the training dataset
ft_all_train_data = []
for idx, row in train_data.iterrows():  # Use the training set
    ft_item = template.format(
        pre=pre,
        context=row['Context'],
        question=row['Question'],
        answer=row['Answer'],
        source=row.get('Source', '')
    )
    ft_all_train_data.append(ft_item)

# Tokenize all the fine-tune data for the training set
tokenized_train_data = []
for el in ft_all_train_data:
    tok_item = tokenizer2(el, padding=True, truncation=True)
    tokenized_train_data.append(tok_item)


# Check for BOS and EOS tokens
print("bos=", tokenizer2.bos_token_id, "eos=", tokenizer2.eos_token_id)

# Check tokenized data examples
print("----tokenized train data----")
print(tokenized_train_data[0])  # Example from the training set

bos= 2 eos= 1
----tokenized train data----
{'input_ids': [2, 651, 2412, 603, 671, 80545, 774, 476, 12836, 1865, 476, 2425, 578, 671, 16481, 20409, 235265, 714, 20409, 798, 3448, 3920, 1105, 62639, 235280, 235269, 948, 12353, 604, 573, 7205, 13137, 64795, 17825, 5031, 235265, 109, 2930, 235292, 108, 4957, 484, 677, 109, 9413, 235292, 108, 11227, 970, 2329, 2076, 791, 577, 2121, 235248, 235315, 235308, 5243, 576, 1277, 3787, 235336, 235248, 109, 1261, 235292, 108, 886, 3309, 235269, 7778, 235265, 62639, 235280, 9286, 674, 476, 2329, 235349, 235256, 51518, 1812, 2004, 4015, 573, 4665, 576, 235248, 235315, 235308, 5243, 576, 3787, 731, 3648, 696, 476, 8080, 576, 30621, 235265, 3428, 576, 573, 30621, 603, 1080, 91923, 24138, 685, 11618, 731, 81135, 611, 573, 8897, 37921, 1816, 1699, 736, 3519, 235269, 575, 2184, 577, 4015, 573, 8691, 24138, 576, 235248, 235315, 235308, 5243, 576, 3787, 235269, 235248, 235315, 235308, 5243, 2004, 1987, 573, 8897, 37921, 235265, 235248, 109, 3154, 235292, 108, 31229, 235290, 18811, 1336, 1029, 28641, 5932, 235262, 8287, 940, 22734, 146647, 7115, 4449, 2954, 3655, 235262, 48422, 235283, 2468, 1336, 54080, 235265, 235254, 3335, 235257, 235265, 2164, 235283, 1854, 1363, 3335, 235257, 235283, 88752, 235290, 63551, 235283, 19895, 235283, 192075, 235298, 35408, 235298, 11146, 235284, 235276, 235274, 235318, 235265, 8490], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [ ]:
# Load the model and tokenizer
model_name = 'google/gemma-2-2b-it'  # Use the name you've given to the model, if applicable
model2, tokenizer2 = load_model_and_tokenizer(model_name)  # Adjust this function as needed

# Move the model to GPU for processing
model2 = model2.to('cpu')

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:
peft_config = LoraConfig(
  task_type=TaskType.CAUSAL_LM,
  inference_mode=False,
  r=4
)
model = get_peft_model(model2, peft_config)
model.print_trainable_parameters()

trainable params: 798,720 || all params: 2,615,140,608 || trainable%: 0.0305

In [ ]:
# Define the directory name
new_dir = "/KaggleX/MWhite"

# Create the directory
os

# Fine tune for 1 epoch

In [ ]:
training_args = TrainingArguments(
    output_dir="/content/drive/MyDrive/KaggleX/MWhite/output/gemma2_essa_ft1",
    learning_rate=2e-4,
    per_device_train_batch_size=1,
    num_train_epochs=1,
    weight_decay=0.0,
    logging_steps=50,
    report_to=None # don't integrate with WANDB
)

trainer = Trainer(
    model=model2,
    args=training_args,
    train_dataset=tokenized_train_data,
    data_collator=transformers.DataCollatorForLanguageModeling(tokenizer2, mlm=False)
)

model2.config.use_cache = False
trainer.train()

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

TrainOutput(global_step=96, training_loss=1.557098627090454, metrics={'train_runtime': 1015.9884, 'train_samples_per_second': 0.094, 'train_steps_per_second': 0.094, 'total_flos': 206959002905088.0, 'train_loss': 1.557098627090454, 'epoch': 1.0})

In [ ]:
# Save the model and tokenizer
trainer.save_model("/content/drive/MyDrive/KaggleX/MWhite/output/gemma2_essa_ft1")  # specify the directory
tokenizer2.save_pretrained("/content/drive/MyDrive/KaggleX/MWhite/output/gemma2_essa_ft1")

('/content/drive/MyDrive/KaggleX/MWhite/output/gemma2_essa_ft1/tokenizer_config.json',
 '/content/drive/MyDrive/KaggleX/MWhite/output/gemma2_essa_ft1/special_tokens_map.json',
 '/content/drive/MyDrive/KaggleX/MWhite/output/gemma2_essa_ft1/tokenizer.model',
 '/content/drive/MyDrive/KaggleX/MWhite/output/gemma2_essa_ft1/added_tokens.json',
 '/content/drive/MyDrive/KaggleX/MWhite/output/gemma2_essa_ft1/tokenizer.json')

In [ ]:
import os

model_path = "/content/drive/MyDrive/KaggleX/MWhite/output/gemma2_essa_ft1"
print(os.listdir(model_path))

['special_tokens_map.json', 'model.safetensors.index.json', 'model-00003-of-00003.safetensors', 'training_args.bin', 'model-00002-of-00003.safetensors', 'tokenizer.model', 'runs', 'config.json', 'tokenizer_config.json', 'model-00001-of-00003.safetensors', 'generation_config.json', 'checkpoint-96', 'tokenizer.json']

# LoRA prompt 1

In [ ]:
# Load the fine-tuned model and tokenizer
model_path = "/content/drive/MyDrive/KaggleX/MWhite/output/gemma2_essa_ft1"
model = AutoModelForCausalLM.from_pretrained(model_path)
tokenizer = AutoTokenizer.from_pretrained(model_path)

# Set the model to evaluation mode
model.eval()

# Define the initial context/preamble
pre_context = "You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act."

# Function to generate a response for a given prompt
def generate_response(prompt):
    # Tokenize the input prompt
    inputs = tokenizer(prompt, return_tensors="pt")

    # Generate a response
    with torch.no_grad():
        outputs = model.generate(inputs["input_ids"], max_length=150, num_return_sequences=1)

    # Decode the generated response
    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return response

# Ask the first question
first_question = f"{pre_context}\n\nWhat is ESSA?"
response_1 = generate_response(first_question)
print("Question 1:", first_question)
print("Response 1:", response_1)

# Scond question
second_question = f"{pre_context}\n\nHow does ESSA impact student achievement?"
response_2 = generate_response(second_question)
print("\nQuestion 2:", second_question)
print("Response 2:", response_2)

# Third question
third_question = f"{pre_context}\n\nWhat is Title I?"
response_3 = generate_response(third_question)
print("\nQuestion 3:", third_question)
print("Response 3:", response_3)

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

Some weights of the model checkpoint at /content/drive/MyDrive/KaggleX/MWhite/output/gemma2_essa_ft1 were not used when initializing Gemma2ForCausalLM: ['model.layers.0.self_attn.q_proj.base_layer.weight', 'model.layers.0.self_attn.q_proj.lora_A.default.weight', 'model.layers.0.self_attn.q_proj.lora_B.default.weight', 'model.layers.0.self_attn.v_proj.base_layer.weight', 'model.layers.0.self_attn.v_proj.lora_A.default.weight', 'model.layers.0.self_attn.v_proj.lora_B.default.weight', 'model.layers.1.self_attn.q_proj.base_layer.weight', 'model.layers.1.self_attn.q_proj.lora_A.default.weight', 'model.layers.1.self_attn.q_proj.lora_B.default.weight', 'model.layers.1.self_attn.v_proj.base_layer.weight', 'model.layers.1.self_attn.v_proj.lora_A.default.weight', 'model.layers.1.self_attn.v_proj.lora_B.default.weight', 'model.layers.10.self_attn.q_proj.base_layer.weight', 'model.layers.10.self_attn.q_proj.lora_A.default.weight', 'model.layers.10.self_attn.q_proj.lora_B.default.weight', 'model.layers.10.self_attn.v_proj.base_layer.weight', 'model.layers.10.self_attn.v_proj.lora_A.default.weight', 'model.layers.10.self_attn.v_proj.lora_B.default.weight', 'model.layers.11.self_attn.q_proj.base_layer.weight', 'model.layers.11.self_attn.q_proj.lora_A.default.weight', 'model.layers.11.self_attn.q_proj.lora_B.default.weight', 'model.layers.11.self_attn.v_proj.base_layer.weight', 'model.layers.11.self_attn.v_proj.lora_A.default.weight', 'model.layers.11.self_attn.v_proj.lora_B.default.weight', 'model.layers.12.self_attn.q_proj.base_layer.weight', 'model.layers.12.self_attn.q_proj.lora_A.default.weight', 'model.layers.12.self_attn.q_proj.lora_B.default.weight', 'model.layers.12.self_attn.v_proj.base_layer.weight', 'model.layers.12.self_attn.v_proj.lora_A.default.weight', 'model.layers.12.self_attn.v_proj.lora_B.default.weight', 'model.layers.13.self_attn.q_proj.base_layer.weight', 'model.layers.13.self_attn.q_proj.lora_A.default.weight', 'model.layers.13.self_attn.q_proj.lora_B.default.weight', 'model.layers.13.self_attn.v_proj.base_layer.weight', 'model.layers.13.self_attn.v_proj.lora_A.default.weight', 'model.layers.13.self_attn.v_proj.lora_B.default.weight', 'model.layers.14.self_attn.q_proj.base_layer.weight', 'model.layers.14.self_attn.q_proj.lora_A.default.weight', 'model.layers.14.self_attn.q_proj.lora_B.default.weight', 'model.layers.14.self_attn.v_proj.base_layer.weight', 'model.layers.14.self_attn.v_proj.lora_A.default.weight', 'model.layers.14.self_attn.v_proj.lora_B.default.weight', 'model.layers.15.self_attn.q_proj.base_layer.weight', 'model.layers.15.self_attn.q_proj.lora_A.default.weight', 'model.layers.15.self_attn.q_proj.lora_B.default.weight', 'model.layers.15.self_attn.v_proj.base_layer.weight', 'model.layers.15.self_attn.v_proj.lora_A.default.weight', 'model.layers.15.self_attn.v_proj.lora_B.default.weight', 'model.layers.16.self_attn.q_proj.base_layer.weight', 'model.layers.16.self_attn.q_proj.lora_A.default.weight', 'model.layers.16.self_attn.q_proj.lora_B.default.weight', 'model.layers.16.self_attn.v_proj.base_layer.weight', 'model.layers.16.self_attn.v_proj.lora_A.default.weight', 'model.layers.16.self_attn.v_proj.lora_B.default.weight', 'model.layers.17.self_attn.q_proj.base_layer.weight', 'model.layers.17.self_attn.q_proj.lora_A.default.weight', 'model.layers.17.self_attn.q_proj.lora_B.default.weight', 'model.layers.17.self_attn.v_proj.base_layer.weight', 'model.layers.17.self_attn.v_proj.lora_A.default.weight', 'model.layers.17.self_attn.v_proj.lora_B.default.weight', 'model.layers.18.self_attn.q_proj.base_layer.weight', 'model.layers.18.self_attn.q_proj.lora_A.default.weight', 'model.layers.18.self_attn.q_proj.lora_B.default.weight', 'model.layers.18.self_attn.v_proj.base_layer.weight', 'model.layers.18.self_attn.v_proj.lora_A.default.weight', 'model.layers.18.self_attn.v_proj.lora_B.default.weight', 'model.layers.19.self_attn.q_proj.base_layer.weight', 'model.layers.19.self_attn.q_proj.lora_A.default.weight', 'model.layers.19.self_attn.q_proj.lora_B.default.weight', 'model.layers.19.self_attn.v_proj.base_layer.weight', 'model.layers.19.self_attn.v_proj.lora_A.default.weight', 'model.layers.19.self_attn.v_proj.lora_B.default.weight', 'model.layers.2.self_attn.q_proj.base_layer.weight', 'model.layers.2.self_attn.q_proj.lora_A.default.weight', 'model.layers.2.self_attn.q_proj.lora_B.default.weight', 'model.layers.2.self_attn.v_proj.base_layer.weight', 'model.layers.2.self_attn.v_proj.lora_A.default.weight', 'model.layers.2.self_attn.v_proj.lora_B.default.weight', 'model.layers.20.self_attn.q_proj.base_layer.weight', 'model.layers.20.self_attn.q_proj.lora_A.default.weight', 'model.layers.20.self_attn.q_proj.lora_B.default.weight', 'model.layers.20.self_attn.v_proj.base_layer.weight', 'model.layers.20.self_attn.v_proj.lora_A.default.weight', 'model.layers.20.self_attn.v_proj.lora_B.default.weight', 'model.layers.21.self_attn.q_proj.base_layer.weight', 'model.layers.21.self_attn.q_proj.lora_A.default.weight', 'model.layers.21.self_attn.q_proj.lora_B.default.weight', 'model.layers.21.self_attn.v_proj.base_layer.weight', 'model.layers.21.self_attn.v_proj.lora_A.default.weight', 'model.layers.21.self_attn.v_proj.lora_B.default.weight', 'model.layers.22.self_attn.q_proj.base_layer.weight', 'model.layers.22.self_attn.q_proj.lora_A.default.weight', 'model.layers.22.self_attn.q_proj.lora_B.default.weight', 'model.layers.22.self_attn.v_proj.base_layer.weight', 'model.layers.22.self_attn.v_proj.lora_A.default.weight', 'model.layers.22.self_attn.v_proj.lora_B.default.weight', 'model.layers.23.self_attn.q_proj.base_layer.weight', 'model.layers.23.self_attn.q_proj.lora_A.default.weight', 'model.layers.23.self_attn.q_proj.lora_B.default.weight', 'model.layers.23.self_attn.v_proj.base_layer.weight', 'model.layers.23.self_attn.v_proj.lora_A.default.weight', 'model.layers.23.self_attn.v_proj.lora_B.default.weight', 'model.layers.24.self_attn.q_proj.base_layer.weight', 'model.layers.24.self_attn.q_proj.lora_A.default.weight', 'model.layers.24.self_attn.q_proj.lora_B.default.weight', 'model.layers.24.self_attn.v_proj.base_layer.weight', 'model.layers.24.self_attn.v_proj.lora_A.default.weight', 'model.layers.24.self_attn.v_proj.lora_B.default.weight', 'model.layers.25.self_attn.q_proj.base_layer.weight', 'model.layers.25.self_attn.q_proj.lora_A.default.weight', 'model.layers.25.self_attn.q_proj.lora_B.default.weight', 'model.layers.25.self_attn.v_proj.base_layer.weight', 'model.layers.25.self_attn.v_proj.lora_A.default.weight', 'model.layers.25.self_attn.v_proj.lora_B.default.weight', 'model.layers.3.self_attn.q_proj.base_layer.weight', 'model.layers.3.self_attn.q_proj.lora_A.default.weight', 'model.layers.3.self_attn.q_proj.lora_B.default.weight', 'model.layers.3.self_attn.v_proj.base_layer.weight', 'model.layers.3.self_attn.v_proj.lora_A.default.weight', 'model.layers.3.self_attn.v_proj.lora_B.default.weight', 'model.layers.4.self_attn.q_proj.base_layer.weight', 'model.layers.4.self_attn.q_proj.lora_A.default.weight', 'model.layers.4.self_attn.q_proj.lora_B.default.weight', 'model.layers.4.self_attn.v_proj.base_layer.weight', 'model.layers.4.self_attn.v_proj.lora_A.default.weight', 'model.layers.4.self_attn.v_proj.lora_B.default.weight', 'model.layers.5.self_attn.q_proj.base_layer.weight', 'model.layers.5.self_attn.q_proj.lora_A.default.weight', 'model.layers.5.self_attn.q_proj.lora_B.default.weight', 'model.layers.5.self_attn.v_proj.base_layer.weight', 'model.layers.5.self_attn.v_proj.lora_A.default.weight', 'model.layers.5.self_attn.v_proj.lora_B.default.weight', 'model.layers.6.self_attn.q_proj.base_layer.weight', 'model.layers.6.self_attn.q_proj.lora_A.default.weight', 'model.layers.6.self_attn.q_proj.lora_B.default.weight', 'model.layers.6.self_attn.v_proj.base_layer.weight', 'model.layers.6.self_attn.v_proj.lora_A.default.weight', 'model.layers.6.self_attn.v_proj.lora_B.default.weight', 'model.layers.7.self_attn.q_proj.base_layer.weight', 'model.layers.7.self_attn.q_proj.lora_A.default.weight', 'model.layers.7.self_attn.q_proj.lora_B.default.weight', 'model.layers.7.self_attn.v_proj.base_layer.weight', 'model.layers.7.self_attn.v_proj.lora_A.default.weight', 'model.layers.7.self_attn.v_proj.lora_B.default.weight', 'model.layers.8.self_attn.q_proj.base_layer.weight', 'model.layers.8.self_attn.q_proj.lora_A.default.weight', 'model.layers.8.self_attn.q_proj.lora_B.default.weight', 'model.layers.8.self_attn.v_proj.base_layer.weight', 'model.layers.8.self_attn.v_proj.lora_A.default.weight', 'model.layers.8.self_attn.v_proj.lora_B.default.weight', 'model.layers.9.self_attn.q_proj.base_layer.weight', 'model.layers.9.self_attn.q_proj.lora_A.default.weight', 'model.layers.9.self_attn.q_proj.lora_B.default.weight', 'model.layers.9.self_attn.v_proj.base_layer.weight', 'model.layers.9.self_attn.v_proj.lora_A.default.weight', 'model.layers.9.self_attn.v_proj.lora_B.default.weight']
- This IS expected if you are initializing Gemma2ForCausalLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Gemma2ForCausalLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of Gemma2ForCausalLM were not initialized from the model checkpoint at /content/drive/MyDrive/KaggleX/MWhite/output/gemma2_essa_ft1 and are newly initialized: ['model.layers.0.self_attn.q_proj.weight', 'model.layers.0.self_attn.v_proj.weight', 'model.layers.1.self_attn.q_proj.weight', 'model.layers.1.self_attn.v_proj.weight', 'model.layers.10.self_attn.q_proj.weight', 'model.layers.10.self_attn.v_proj.weight', 'model.layers.11.self_attn.q_proj.weight', 'model.layers.11.self_attn.v_proj.weight', 'model.layers.12.self_attn.q_proj.weight', 'model.layers.12.self_attn.v_proj.weight', 'model.layers.13.self_attn.q_proj.weight', 'model.layers.13.self_attn.v_proj.weight', 'model.layers.14.self_attn.q_proj.weight', 'model.layers.14.self_attn.v_proj.weight', 'model.layers.15.self_attn.q_proj.weight', 'model.layers.15.self_attn.v_proj.weight', 'model.layers.16.self_attn.q_proj.weight', 'model.layers.16.self_attn.v_proj.weight', 'model.layers.17.self_attn.q_proj.weight', 'model.layers.17.self_attn.v_proj.weight', 'model.layers.18.self_attn.q_proj.weight', 'model.layers.18.self_attn.v_proj.weight', 'model.layers.19.self_attn.q_proj.weight', 'model.layers.19.self_attn.v_proj.weight', 'model.layers.2.self_attn.q_proj.weight', 'model.layers.2.self_attn.v_proj.weight', 'model.layers.20.self_attn.q_proj.weight', 'model.layers.20.self_attn.v_proj.weight', 'model.layers.21.self_attn.q_proj.weight', 'model.layers.21.self_attn.v_proj.weight', 'model.layers.22.self_attn.q_proj.weight', 'model.layers.22.self_attn.v_proj.weight', 'model.layers.23.self_attn.q_proj.weight', 'model.layers.23.self_attn.v_proj.weight', 'model.layers.24.self_attn.q_proj.weight', 'model.layers.24.self_attn.v_proj.weight', 'model.layers.25.self_attn.q_proj.weight', 'model.layers.25.self_attn.v_proj.weight', 'model.layers.3.self_attn.q_proj.weight', 'model.layers.3.self_attn.v_proj.weight', 'model.layers.4.self_attn.q_proj.weight', 'model.layers.4.self_attn.v_proj.weight', 'model.layers.5.self_attn.q_proj.weight', 'model.layers.5.self_attn.v_proj.weight', 'model.layers.6.self_attn.q_proj.weight', 'model.layers.6.self_attn.v_proj.weight', 'model.layers.7.self_attn.q_proj.weight', 'model.layers.7.self_attn.v_proj.weight', 'model.layers.8.self_attn.q_proj.weight', 'model.layers.8.self_attn.v_proj.weight', 'model.layers.9.self_attn.q_proj.weight', 'model.layers.9.self_attn.v_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Question 1: You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act.

What is ESSA?
Response 1: You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act.

What is ESSA?のでしょう-complexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContent الدولىNewswireGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUMGEBURTSDATUM

Question 2: You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act.

How does ESSA impact student achievement?
Response 2: You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act.

How does ESSA impact student achievement?complexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContentcomplexContent:ear godk quittAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelperAddTagHelper

Question 3: You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act.

What is Title I?
Response 3: You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act.

What is Title I?tamina Kenya styleSuspendLayoutSuspendLayoutSuspendLayoutSuspendLayoutSuspendLayoutSuspendLayoutSuspendLayoutSuspendLayoutSuspendLayoutSuspendLayoutSuspendLayoutSuspendLayoutSuspendLayoutSuspendLayoutSuspendLayoutSuspendLayoutSuspendLayoutSuspendLayoutSuspendLayoutValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyleValueStyle

Complete gibberish, but it could be that I called the wrong tokenizer with 1 epoch. Will try with 4 now.

## Fine-tune using LoRA, 4 epochs

In [ ]:
peft_config = LoraConfig(
  task_type=TaskType.CAUSAL_LM,
  inference_mode=False,
  r=4 # match our keras experiment
)
model = get_peft_model(model2, peft_config)

# Define training arguments
training_args = TrainingArguments(
    output_dir="/content/drive/MyDrive/KaggleX/MWhite/output/gemma2_essa_ft2",
    learning_rate=2e-4,
    per_device_train_batch_size=1,
    num_train_epochs=4,
    weight_decay=0.0,
    logging_steps=100,
    report_to=None  # Don't integrate with WANDB
)


# Initialize the Trainer
trainer = Trainer(
    model=model2,  # Best model so far
    args=training_args,
    train_dataset=tokenized_train_data,
    data_collator=DataCollatorForLanguageModeling(tokenizer2, mlm=False)
)

# Disable caching for training
model2.config.use_cache = False

trainer.train()

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

TrainOutput(global_step=384, training_loss=1.2558056712150574, metrics={'train_runtime': 4682.1288, 'train_samples_per_second': 0.082, 'train_steps_per_second': 0.082, 'total_flos': 827836011620352.0, 'train_loss': 1.2558056712150574, 'epoch': 4.0})

# LoRA prompt responses, 4 epochs

In [ ]:
# Step 1: Save the model and tokenizer after training
trainer.save_model("/content/drive/MyDrive/KaggleX/MWhite/output/gemma2_essa_ft2")
tokenizer2.save_pretrained("/content/drive/MyDrive/KaggleX/MWhite/output/gemma2_essa_ft2")

# Step 2: Load the model and tokenizer
model = AutoModelForCausalLM.from_pretrained("/content/drive/MyDrive/KaggleX/MWhite/output/gemma2_essa_ft2")
tokenizer = AutoTokenizer.from_pretrained("/content/drive/MyDrive/KaggleX/MWhite/output/gemma2_essa_ft2")

# Set the model to evaluation mode
model.eval()

# Define the initial context/preamble
pre_context = "You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act."

# Function to generate a response for a given prompt
def generate_response(prompt):
    # Tokenize the input prompt
    inputs = tokenizer(prompt, return_tensors="pt")

    # Generate a response
    with torch.no_grad():
        outputs = model.generate(inputs["input_ids"], max_length=150, num_return_sequences=1)

    # Decode the generated response
    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return response

# Ask the first question
first_question = f"{pre_context}\n\nWhat is ESSA?"
response_1 = generate_response(first_question)
print("Question 1:", first_question)
print("Response 1:", response_1)

# Scond question
second_question = f"{pre_context}\n\nHow does ESSA impact student achievement?"
response_2 = generate_response(second_question)
print("\nQuestion 2:", second_question)
print("Response 2:", response_2)

# Third question
third_question = f"{pre_context}\n\nWhat is Title I?"
response_3 = generate_response(third_question)
print("\nQuestion 3:", third_question)
print("Response 3:", response_3)

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

Some weights of the model checkpoint at /content/drive/MyDrive/KaggleX/MWhite/output/gemma2_essa_ft2 were not used when initializing Gemma2ForCausalLM: ['model.layers.0.self_attn.q_proj.base_layer.weight', 'model.layers.0.self_attn.q_proj.lora_A.default.weight', 'model.layers.0.self_attn.q_proj.lora_B.default.weight', 'model.layers.0.self_attn.v_proj.base_layer.weight', 'model.layers.0.self_attn.v_proj.lora_A.default.weight', 'model.layers.0.self_attn.v_proj.lora_B.default.weight', 'model.layers.1.self_attn.q_proj.base_layer.weight', 'model.layers.1.self_attn.q_proj.lora_A.default.weight', 'model.layers.1.self_attn.q_proj.lora_B.default.weight', 'model.layers.1.self_attn.v_proj.base_layer.weight', 'model.layers.1.self_attn.v_proj.lora_A.default.weight', 'model.layers.1.self_attn.v_proj.lora_B.default.weight', 'model.layers.10.self_attn.q_proj.base_layer.weight', 'model.layers.10.self_attn.q_proj.lora_A.default.weight', 'model.layers.10.self_attn.q_proj.lora_B.default.weight', 'model.layers.10.self_attn.v_proj.base_layer.weight', 'model.layers.10.self_attn.v_proj.lora_A.default.weight', 'model.layers.10.self_attn.v_proj.lora_B.default.weight', 'model.layers.11.self_attn.q_proj.base_layer.weight', 'model.layers.11.self_attn.q_proj.lora_A.default.weight', 'model.layers.11.self_attn.q_proj.lora_B.default.weight', 'model.layers.11.self_attn.v_proj.base_layer.weight', 'model.layers.11.self_attn.v_proj.lora_A.default.weight', 'model.layers.11.self_attn.v_proj.lora_B.default.weight', 'model.layers.12.self_attn.q_proj.base_layer.weight', 'model.layers.12.self_attn.q_proj.lora_A.default.weight', 'model.layers.12.self_attn.q_proj.lora_B.default.weight', 'model.layers.12.self_attn.v_proj.base_layer.weight', 'model.layers.12.self_attn.v_proj.lora_A.default.weight', 'model.layers.12.self_attn.v_proj.lora_B.default.weight', 'model.layers.13.self_attn.q_proj.base_layer.weight', 'model.layers.13.self_attn.q_proj.lora_A.default.weight', 'model.layers.13.self_attn.q_proj.lora_B.default.weight', 'model.layers.13.self_attn.v_proj.base_layer.weight', 'model.layers.13.self_attn.v_proj.lora_A.default.weight', 'model.layers.13.self_attn.v_proj.lora_B.default.weight', 'model.layers.14.self_attn.q_proj.base_layer.weight', 'model.layers.14.self_attn.q_proj.lora_A.default.weight', 'model.layers.14.self_attn.q_proj.lora_B.default.weight', 'model.layers.14.self_attn.v_proj.base_layer.weight', 'model.layers.14.self_attn.v_proj.lora_A.default.weight', 'model.layers.14.self_attn.v_proj.lora_B.default.weight', 'model.layers.15.self_attn.q_proj.base_layer.weight', 'model.layers.15.self_attn.q_proj.lora_A.default.weight', 'model.layers.15.self_attn.q_proj.lora_B.default.weight', 'model.layers.15.self_attn.v_proj.base_layer.weight', 'model.layers.15.self_attn.v_proj.lora_A.default.weight', 'model.layers.15.self_attn.v_proj.lora_B.default.weight', 'model.layers.16.self_attn.q_proj.base_layer.weight', 'model.layers.16.self_attn.q_proj.lora_A.default.weight', 'model.layers.16.self_attn.q_proj.lora_B.default.weight', 'model.layers.16.self_attn.v_proj.base_layer.weight', 'model.layers.16.self_attn.v_proj.lora_A.default.weight', 'model.layers.16.self_attn.v_proj.lora_B.default.weight', 'model.layers.17.self_attn.q_proj.base_layer.weight', 'model.layers.17.self_attn.q_proj.lora_A.default.weight', 'model.layers.17.self_attn.q_proj.lora_B.default.weight', 'model.layers.17.self_attn.v_proj.base_layer.weight', 'model.layers.17.self_attn.v_proj.lora_A.default.weight', 'model.layers.17.self_attn.v_proj.lora_B.default.weight', 'model.layers.18.self_attn.q_proj.base_layer.weight', 'model.layers.18.self_attn.q_proj.lora_A.default.weight', 'model.layers.18.self_attn.q_proj.lora_B.default.weight', 'model.layers.18.self_attn.v_proj.base_layer.weight', 'model.layers.18.self_attn.v_proj.lora_A.default.weight', 'model.layers.18.self_attn.v_proj.lora_B.default.weight', 'model.layers.19.self_attn.q_proj.base_layer.weight', 'model.layers.19.self_attn.q_proj.lora_A.default.weight', 'model.layers.19.self_attn.q_proj.lora_B.default.weight', 'model.layers.19.self_attn.v_proj.base_layer.weight', 'model.layers.19.self_attn.v_proj.lora_A.default.weight', 'model.layers.19.self_attn.v_proj.lora_B.default.weight', 'model.layers.2.self_attn.q_proj.base_layer.weight', 'model.layers.2.self_attn.q_proj.lora_A.default.weight', 'model.layers.2.self_attn.q_proj.lora_B.default.weight', 'model.layers.2.self_attn.v_proj.base_layer.weight', 'model.layers.2.self_attn.v_proj.lora_A.default.weight', 'model.layers.2.self_attn.v_proj.lora_B.default.weight', 'model.layers.20.self_attn.q_proj.base_layer.weight', 'model.layers.20.self_attn.q_proj.lora_A.default.weight', 'model.layers.20.self_attn.q_proj.lora_B.default.weight', 'model.layers.20.self_attn.v_proj.base_layer.weight', 'model.layers.20.self_attn.v_proj.lora_A.default.weight', 'model.layers.20.self_attn.v_proj.lora_B.default.weight', 'model.layers.21.self_attn.q_proj.base_layer.weight', 'model.layers.21.self_attn.q_proj.lora_A.default.weight', 'model.layers.21.self_attn.q_proj.lora_B.default.weight', 'model.layers.21.self_attn.v_proj.base_layer.weight', 'model.layers.21.self_attn.v_proj.lora_A.default.weight', 'model.layers.21.self_attn.v_proj.lora_B.default.weight', 'model.layers.22.self_attn.q_proj.base_layer.weight', 'model.layers.22.self_attn.q_proj.lora_A.default.weight', 'model.layers.22.self_attn.q_proj.lora_B.default.weight', 'model.layers.22.self_attn.v_proj.base_layer.weight', 'model.layers.22.self_attn.v_proj.lora_A.default.weight', 'model.layers.22.self_attn.v_proj.lora_B.default.weight', 'model.layers.23.self_attn.q_proj.base_layer.weight', 'model.layers.23.self_attn.q_proj.lora_A.default.weight', 'model.layers.23.self_attn.q_proj.lora_B.default.weight', 'model.layers.23.self_attn.v_proj.base_layer.weight', 'model.layers.23.self_attn.v_proj.lora_A.default.weight', 'model.layers.23.self_attn.v_proj.lora_B.default.weight', 'model.layers.24.self_attn.q_proj.base_layer.weight', 'model.layers.24.self_attn.q_proj.lora_A.default.weight', 'model.layers.24.self_attn.q_proj.lora_B.default.weight', 'model.layers.24.self_attn.v_proj.base_layer.weight', 'model.layers.24.self_attn.v_proj.lora_A.default.weight', 'model.layers.24.self_attn.v_proj.lora_B.default.weight', 'model.layers.25.self_attn.q_proj.base_layer.weight', 'model.layers.25.self_attn.q_proj.lora_A.default.weight', 'model.layers.25.self_attn.q_proj.lora_B.default.weight', 'model.layers.25.self_attn.v_proj.base_layer.weight', 'model.layers.25.self_attn.v_proj.lora_A.default.weight', 'model.layers.25.self_attn.v_proj.lora_B.default.weight', 'model.layers.3.self_attn.q_proj.base_layer.weight', 'model.layers.3.self_attn.q_proj.lora_A.default.weight', 'model.layers.3.self_attn.q_proj.lora_B.default.weight', 'model.layers.3.self_attn.v_proj.base_layer.weight', 'model.layers.3.self_attn.v_proj.lora_A.default.weight', 'model.layers.3.self_attn.v_proj.lora_B.default.weight', 'model.layers.4.self_attn.q_proj.base_layer.weight', 'model.layers.4.self_attn.q_proj.lora_A.default.weight', 'model.layers.4.self_attn.q_proj.lora_B.default.weight', 'model.layers.4.self_attn.v_proj.base_layer.weight', 'model.layers.4.self_attn.v_proj.lora_A.default.weight', 'model.layers.4.self_attn.v_proj.lora_B.default.weight', 'model.layers.5.self_attn.q_proj.base_layer.weight', 'model.layers.5.self_attn.q_proj.lora_A.default.weight', 'model.layers.5.self_attn.q_proj.lora_B.default.weight', 'model.layers.5.self_attn.v_proj.base_layer.weight', 'model.layers.5.self_attn.v_proj.lora_A.default.weight', 'model.layers.5.self_attn.v_proj.lora_B.default.weight', 'model.layers.6.self_attn.q_proj.base_layer.weight', 'model.layers.6.self_attn.q_proj.lora_A.default.weight', 'model.layers.6.self_attn.q_proj.lora_B.default.weight', 'model.layers.6.self_attn.v_proj.base_layer.weight', 'model.layers.6.self_attn.v_proj.lora_A.default.weight', 'model.layers.6.self_attn.v_proj.lora_B.default.weight', 'model.layers.7.self_attn.q_proj.base_layer.weight', 'model.layers.7.self_attn.q_proj.lora_A.default.weight', 'model.layers.7.self_attn.q_proj.lora_B.default.weight', 'model.layers.7.self_attn.v_proj.base_layer.weight', 'model.layers.7.self_attn.v_proj.lora_A.default.weight', 'model.layers.7.self_attn.v_proj.lora_B.default.weight', 'model.layers.8.self_attn.q_proj.base_layer.weight', 'model.layers.8.self_attn.q_proj.lora_A.default.weight', 'model.layers.8.self_attn.q_proj.lora_B.default.weight', 'model.layers.8.self_attn.v_proj.base_layer.weight', 'model.layers.8.self_attn.v_proj.lora_A.default.weight', 'model.layers.8.self_attn.v_proj.lora_B.default.weight', 'model.layers.9.self_attn.q_proj.base_layer.weight', 'model.layers.9.self_attn.q_proj.lora_A.default.weight', 'model.layers.9.self_attn.q_proj.lora_B.default.weight', 'model.layers.9.self_attn.v_proj.base_layer.weight', 'model.layers.9.self_attn.v_proj.lora_A.default.weight', 'model.layers.9.self_attn.v_proj.lora_B.default.weight']
- This IS expected if you are initializing Gemma2ForCausalLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing Gemma2ForCausalLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of Gemma2ForCausalLM were not initialized from the model checkpoint at /content/drive/MyDrive/KaggleX/MWhite/output/gemma2_essa_ft2 and are newly initialized: ['model.layers.0.self_attn.q_proj.weight', 'model.layers.0.self_attn.v_proj.weight', 'model.layers.1.self_attn.q_proj.weight', 'model.layers.1.self_attn.v_proj.weight', 'model.layers.10.self_attn.q_proj.weight', 'model.layers.10.self_attn.v_proj.weight', 'model.layers.11.self_attn.q_proj.weight', 'model.layers.11.self_attn.v_proj.weight', 'model.layers.12.self_attn.q_proj.weight', 'model.layers.12.self_attn.v_proj.weight', 'model.layers.13.self_attn.q_proj.weight', 'model.layers.13.self_attn.v_proj.weight', 'model.layers.14.self_attn.q_proj.weight', 'model.layers.14.self_attn.v_proj.weight', 'model.layers.15.self_attn.q_proj.weight', 'model.layers.15.self_attn.v_proj.weight', 'model.layers.16.self_attn.q_proj.weight', 'model.layers.16.self_attn.v_proj.weight', 'model.layers.17.self_attn.q_proj.weight', 'model.layers.17.self_attn.v_proj.weight', 'model.layers.18.self_attn.q_proj.weight', 'model.layers.18.self_attn.v_proj.weight', 'model.layers.19.self_attn.q_proj.weight', 'model.layers.19.self_attn.v_proj.weight', 'model.layers.2.self_attn.q_proj.weight', 'model.layers.2.self_attn.v_proj.weight', 'model.layers.20.self_attn.q_proj.weight', 'model.layers.20.self_attn.v_proj.weight', 'model.layers.21.self_attn.q_proj.weight', 'model.layers.21.self_attn.v_proj.weight', 'model.layers.22.self_attn.q_proj.weight', 'model.layers.22.self_attn.v_proj.weight', 'model.layers.23.self_attn.q_proj.weight', 'model.layers.23.self_attn.v_proj.weight', 'model.layers.24.self_attn.q_proj.weight', 'model.layers.24.self_attn.v_proj.weight', 'model.layers.25.self_attn.q_proj.weight', 'model.layers.25.self_attn.v_proj.weight', 'model.layers.3.self_attn.q_proj.weight', 'model.layers.3.self_attn.v_proj.weight', 'model.layers.4.self_attn.q_proj.weight', 'model.layers.4.self_attn.v_proj.weight', 'model.layers.5.self_attn.q_proj.weight', 'model.layers.5.self_attn.v_proj.weight', 'model.layers.6.self_attn.q_proj.weight', 'model.layers.6.self_attn.v_proj.weight', 'model.layers.7.self_attn.q_proj.weight', 'model.layers.7.self_attn.v_proj.weight', 'model.layers.8.self_attn.q_proj.weight', 'model.layers.8.self_attn.v_proj.weight', 'model.layers.9.self_attn.q_proj.weight', 'model.layers.9.self_attn.v_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Question 1: You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act.

What is ESSA?
Response 1: You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act.

GeneratedValueGeneratedValueGeneratedValueGeneratedValueGeneratedValueGeneratedValueGeneratedValueGeneratedValueGeneratedValueGeneratedValueGeneratedValueGeneratedValueGeneratedValueGeneratedValueGeneratedValueGeneratedValueGeneratedValueTagHelpersTagHelpersTagHelpersTagHelpersTagHelpers>  spoken Kreuz '"' '"' '"' '"' '"' '"' '"' '"' '"' '"' '"' '"' '"' '"' '"' '"' '"' '"' '"' '"' '"' '"' '"'

Question 2: You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act.

How does ESSA impact student achievement?
Response 2: You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act.

How does ESSA impact student achievement? perfectamente perfectamente perfectamente could****themenuStripmenuStripmenuStripmenuStrip the lives be. Einf Einf što što što što što što što što što što što što što što štohttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttpshttphttps

Question 3: You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act.

What is Title I?
Response 3: You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act.

What is Title I? fout fout fout fout fout fout foutvaadinvaadinvaadinvaadinvaadinvaadinvaadinvaadinvaadinvaadinvaadinvaadinvaadinvaadinvaadinvaadinvaadinvaadinintGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatstGeplaatst

# I have no idea why this is so bad. **Share with GW**

## Prior LoRA responses

In [ ]:
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

# Load the fine-tuned model and tokenizer
model_path = "/content/drive/MyDrive/Kaggle_X/Mary_ESSA/output/gemma2_essa_ft1"
model = AutoModelForCausalLM.from_pretrained(model_path)
tokenizer = AutoTokenizer.from_pretrained(model_path)

# Set the model to evaluation mode
model.eval()

# Define the initial context/preamble
pre_context = "You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act."

# Function to generate a response for a given prompt
def generate_response(prompt):
    # Tokenize the input prompt
    inputs = tokenizer(prompt, return_tensors="pt")

    # Generate a response
    with torch.no_grad():
        outputs = model.generate(inputs["input_ids"], max_length=150, num_return_sequences=1)

    # Decode the generated response
    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return response

# Ask the first question
first_question = f"{pre_context}\n\nWhat is ESSA?"
response_1 = generate_response(first_question)
print("Question 1:", first_question)
print("Response 1:", response_1)

# Scond question
second_question = "How does ESSA impact student achievement?"
response_2 = generate_response(second_question)
print("\nQuestion 2:", second_question)
print("Response 2:", response_2)

# Third question
third_question = "What is Title I?"
response_3 = generate_response(third_question)
print("\nQuestion 3:", third_question)
print("Response 3:", response_3)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Question 1: You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act.

What is ESSA?
Response 1: You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act.

What is ESSA?

ESSA is a federal law that was passed in 2015. It replaced the No Child Left Behind Act (NCLB).

What are the main goals of ESSA?

The main goals of ESSA are to:

* **Improve student achievement:** ESSA aims to ensure that all students, regardless of their background, have the opportunity to succeed in school.
* **Increase accountability:** ESSA requires states to set high standards for student achievement and to hold schools accountable for meeting those standards.
* **Promote flexibility:** ESSA gives states more flexibility in how

Question 2: How does ESSA impact student achievement?
Response 2: How does ESSA impact student achievement?

The Every Student Succeeds Act (ESSA) has had a significant impact on student achievement, but its effects are complex and multifaceted. Here's a breakdown of its key impacts:

**Positive Impacts:**

* **Increased Flexibility:** ESSA provides states with more flexibility in designing their own education systems, allowing them to tailor programs to their specific needs and resources. This has led to the development of innovative approaches to teaching and learning, such as personalized learning, project-based learning, and STEM education.
* **Focus on Data-Driven Decision Making:** ESSA emphasizes the use of data to inform decision-making at all levels of education. This has led to a greater focus on student achievement

Question 3: What is Title I?
Response 3: What is Title I?

Title I of the Elementary and Secondary Education Act of 1965 is a federal program that provides financial assistance to schools with a high percentage of low-income students. The program is designed to help schools meet the educational needs of these students and to close the achievement gap between low-income students and their more affluent peers.

Here's a breakdown of Title I:

**Purpose:**

* To ensure that all children have access to a high-quality education, regardless of their family's income.
* To provide additional resources to schools with high concentrations of low-income students.
* To help schools improve the academic performance of their students.

**Funding:**

* Title I funds

Evaluation of LoRA results, looks good. Can even capture Title I which wasn't totally in base dataset.

In [ ]:
# With Gemma2 base 2b-it, the function loads and merges the LORA adapter weights.
model, tokenizer = load_lora_model("google/gemma-2-2b-it", lora_save_path)
model = model.to('cpu')

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

#RAG implementation

# Install additional RAG libraries and tools

In [ ]:
!pip install python-docx langchain

Requirement already satisfied: python-docx in /usr/local/lib/python3.10/dist-packages (1.1.2)
Requirement already satisfied: langchain in /usr/local/lib/python3.10/dist-packages (0.3.7)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from python-docx) (5.3.0)
Requirement already satisfied: typing-extensions>=4.9.0 in /usr/local/lib/python3.10/dist-packages (from python-docx) (4.12.2)
Requirement already satisfied: PyYAML>=5.3 in /usr/local/lib/python3.10/dist-packages (from langchain) (6.0.2)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /usr/local/lib/python3.10/dist-packages (from langchain) (2.0.35)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.10/dist-packages (from langchain) (3.10.10)
Requirement already satisfied: async-timeout<5.0.0,>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from langchain) (4.0.3)
Requirement already satisfied: langchain-core<0.4.0,>=0.3.15 in /usr/local/lib/python3.10/dist-packages (from langchain) (0.3.16)
Requirement already satisfied: langchain-text-splitters<0.4.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from langchain) (0.3.2)
Requirement already satisfied: langsmith<0.2.0,>=0.1.17 in /usr/local/lib/python3.10/dist-packages (from langchain) (0.1.142)
Requirement already satisfied: numpy<2,>=1 in /usr/local/lib/python3.10/dist-packages (from langchain) (1.26.4)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.10/dist-packages (from langchain) (2.9.2)
Requirement already satisfied: requests<3,>=2 in /usr/local/lib/python3.10/dist-packages (from langchain) (2.32.3)
Requirement already satisfied: tenacity!=8.4.0,<10,>=8.1.0 in /usr/local/lib/python3.10/dist-packages (from langchain) (9.0.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (2.4.3)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (6.1.0)
Requirement already satisfied: yarl<2.0,>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (1.17.1)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /usr/local/lib/python3.10/dist-packages (from langchain-core<0.4.0,>=0.3.15->langchain) (1.33)
Requirement already satisfied: packaging<25,>=23.2 in /usr/local/lib/python3.10/dist-packages (from langchain-core<0.4.0,>=0.3.15->langchain) (24.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from langsmith<0.2.0,>=0.1.17->langchain) (0.27.2)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in /usr/local/lib/python3.10/dist-packages (from langsmith<0.2.0,>=0.1.17->langchain) (3.10.11)
Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from langsmith<0.2.0,>=0.1.17->langchain) (1.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in /usr/local/lib/python3.10/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.23.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain) (2024.8.30)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from SQLAlchemy<3,>=1.4->langchain) (3.1.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain) (3.7.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain) (1.0.6)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain) (1.3.1)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain) (0.14.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.10/dist-packages (from jsonpatch<2.0,>=1.33->langchain-core<0.4.0,>=0.3.15->langchain) (3.0.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from yarl<2.0,>=1.12.0->aiohttp<4.0.0,>=3.8.3->langchain) (0.2.0)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio->httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain) (1.2.2)

In [ ]:
import langchain
import pandas as pd

In [ ]:
from langchain.schema import Document as LangchainDocument
from langchain.text_splitter import CharacterTextSplitter
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import Chroma
from transformers import pipeline

In [ ]:
pip install pandas openpyxl

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (3.1.5)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

# Import and manage RAG file

In [ ]:
uploaded = files.upload()

Saving ESSA RAG file_10.31.xlsx to ESSA RAG file_10.31.xlsx

In [ ]:
# Load the Excel file
xls_file = "ESSA RAG file_10.31.xlsx"

# Read the entire Excel file
df = pd.read_excel(xls_file)

for idx, row in df.iterrows():
  txt = DocumentWithText(row['Question'] + ' ' + row['Answer'])
  texts.append(txt)

print("Number of items=", len(texts))

# Debugging - print all the items
#for txt in texts:
#  print(txt.page_content)

# Create embeddings and vector store
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

# Create a Chroma vector database from the documents
# Important: Make sure to delete previous db (if any) or else retrieval returns lots of duplicates :)
try:
  db.delete_collection()
except:
  pass
db = Chroma.from_documents(texts, embeddings)

# Create a retriever from the vector database
# NOTE: You need to experiment with retrieval parameters
retriever = db.as_retriever(search_type="similarity_score_threshold", search_kwargs={"k": 2, "score_threshold": 0.5})

Number of items= 204

In [ ]:
#Test the RAG retriever on a prompt

docs = retriever.invoke("What is ESSA?")
print("retreived", len(docs), "documents")
print(docs)

retreived 2 documents
[Document(metadata={}, page_content='What is ESSA? ESSA is the\xa0federal law\xa0that allows the U.S. Government to support both national and local education goals with grants and other resources. Passed in 2015, it replaced\xa0No Child Left Behind (NCLB).\xa0and became\xa0the latest\xa0iteration, or extension, of the 1965\xa0Elementary and Secondary Education Act.'), Document(metadata={}, page_content='What is an ESSA State Plan? An ESSA State Plan is a comprehensive document developed by each U.S. state to outline how it will implement the Every Student Succeeds Act (ESSA). ESSA, enacted in December 2015, is a federal law that governs the United States K-12 public education policy.')]

# Prompt responses after RAG

In [ ]:
# Load a separate QA pipeline
qa_pipeline = pipeline("question-answering", model="distilbert-base-uncased-distilled-squad")

# Function to get answer from the model using relevant context
def get_answer(query):
    # Use the retriever to find relevant documents
    relevant_docs = retriever.get_relevant_documents(query)  # Changed invoke to retrieve

    if not relevant_docs:
        return "No relevant context found for answering the question."

    # Combine the text from relevant documents to create a coherent context
    context_chunk = "\n".join([doc.page_content for doc in relevant_docs])

    # Use the QA pipeline to get an answer
    response = qa_pipeline(question=query, context=context_chunk)

    # Return the answer found by the QA model
    return response['answer']

    # Example usage of the function
query = "What is ESSA?"
result = get_answer(query)
print("Answer:", result)

Answer: federal law

In [ ]:
# Ssecond question
query2 = "What is Title I?"
result2 = get_answer(query2)

# Result for the second question
print("Second Question:", query2)
print("Answer:", result2)

WARNING:langchain_core.vectorstores.base:No relevant docs were retrieved using the relevance score threshold 0.5

Second Question: What is Title I?
Answer: No relevant context found for answering the question.

In [ ]:
# Third question
query3 = "What does ESSA say about state assessments?"
result3 = get_answer(query3)

# Result for the second question
print("Third Question:", query3)
print("Answer:", result3)

Third Question: What does ESSA say about state assessments?
Answer: Provide for participation in the assessments of all students in the grades assessed

RAG results are short and not very elaborate or clear.

#Gradio Interface

In [ ]:
!pip install gradio

Collecting gradio
  Downloading gradio-5.5.0-py3-none-any.whl.metadata (16 kB)
Collecting aiofiles<24.0,>=22.0 (from gradio)
  Downloading aiofiles-23.2.1-py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (3.7.1)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in /usr/local/lib/python3.10/dist-packages (from gradio) (0.115.5)
Collecting ffmpy (from gradio)
  Downloading ffmpy-0.4.0-py3-none-any.whl.metadata (2.9 kB)
Collecting gradio-client==1.4.2 (from gradio)
  Downloading gradio_client-1.4.2-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: httpx>=0.24.1 in /usr/local/lib/python3.10/dist-packages (from gradio) (0.27.2)
Requirement already satisfied: huggingface-hub>=0.25.1 in /usr/local/lib/python3.10/dist-packages (from gradio) (0.26.2)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (3.1.4)
Collecting markupsafe~=2.0 (from gradio)
  Downloading MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: numpy<3.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (1.26.4)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (3.10.11)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from gradio) (24.2)
Requirement already satisfied: pandas<3.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (2.2.2)
Requirement already satisfied: pillow<12.0,>=8.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (11.0.0)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (2.9.2)
Collecting pydub (from gradio)
  Downloading pydub-0.25.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting python-multipart==0.0.12 (from gradio)
  Downloading python_multipart-0.0.12-py3-none-any.whl.metadata (1.9 kB)
Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (6.0.2)
Collecting ruff>=0.2.2 (from gradio)
  Downloading ruff-0.7.3-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (25 kB)
Collecting safehttpx<1.0,>=0.1.1 (from gradio)
  Downloading safehttpx-0.1.1-py3-none-any.whl.metadata (4.1 kB)
Collecting semantic-version~=2.0 (from gradio)
  Downloading semantic_version-2.10.0-py2.py3-none-any.whl.metadata (9.7 kB)
Requirement already satisfied: starlette<1.0,>=0.40.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (0.41.2)
Collecting tomlkit==0.12.0 (from gradio)
  Downloading tomlkit-0.12.0-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: typer<1.0,>=0.12 in /usr/local/lib/python3.10/dist-packages (from gradio) (0.13.0)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (4.12.2)
Requirement already satisfied: uvicorn>=0.14.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (0.32.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from gradio-client==1.4.2->gradio) (2024.9.0)
Collecting websockets<13.0,>=10.0 (from gradio-client==1.4.2->gradio)
  Downloading websockets-12.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.10/dist-packages (from anyio<5.0,>=3.0->gradio) (3.10)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.10/dist-packages (from anyio<5.0,>=3.0->gradio) (1.3.1)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<5.0,>=3.0->gradio) (1.2.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx>=0.24.1->gradio) (2024.8.30)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx>=0.24.1->gradio) (1.0.6)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx>=0.24.1->gradio) (0.14.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.25.1->gradio) (3.16.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.25.1->gradio) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.25.1->gradio) (4.66.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0,>=1.0->gradio) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0,>=1.0->gradio) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0,>=1.0->gradio) (2024.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic>=2.0->gradio) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in /usr/local/lib/python3.10/dist-packages (from pydantic>=2.0->gradio) (2.23.4)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0,>=0.12->gradio) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0,>=0.12->gradio) (13.9.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas<3.0,>=1.0->gradio) (1.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.18.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.25.1->gradio) (3.4.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.25.1->gradio) (2.2.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0,>=0.12->gradio) (0.1.2)
Downloading gradio-5.5.0-py3-none-any.whl (56.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.7/56.7 MB 22.4 MB/s eta 0:00:00
Downloading gradio_client-1.4.2-py3-none-any.whl (319 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 319.8/319.8 kB 16.0 MB/s eta 0:00:00
Downloading python_multipart-0.0.12-py3-none-any.whl (23 kB)
Downloading tomlkit-0.12.0-py3-none-any.whl (37 kB)
Downloading aiofiles-23.2.1-py3-none-any.whl (15 kB)
Downloading MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Downloading ruff-0.7.3-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 100.5 MB/s eta 0:00:00
Downloading safehttpx-0.1.1-py3-none-any.whl (8.4 kB)
Downloading semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
Downloading ffmpy-0.4.0-py3-none-any.whl (5.8 kB)
Downloading pydub-0.25.1-py2.py3-none-any.whl (32 kB)
Downloading websockets-12.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (130 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 7.4 MB/s eta 0:00:00
Installing collected packages: pydub, websockets, tomlkit, semantic-version, ruff, python-multipart, markupsafe, ffmpy, aiofiles, safehttpx, gradio-client, gradio
  Attempting uninstall: websockets
    Found existing installation: websockets 14.1
    Uninstalling websockets-14.1:
      Successfully uninstalled websockets-14.1
  Attempting uninstall: markupsafe
    Found existing installation: MarkupSafe 3.0.2
    Uninstalling MarkupSafe-3.0.2:
      Successfully uninstalled MarkupSafe-3.0.2
Successfully installed aiofiles-23.2.1 ffmpy-0.4.0 gradio-5.5.0 gradio-client-1.4.2 markupsafe-2.1.5 pydub-0.25.1 python-multipart-0.0.12 ruff-0.7.3 safehttpx-0.1.1 semantic-version-2.10.0 tomlkit-0.12.0 websockets-12.0

In [ ]:
import os
import pandas as pd
import gradio as gr
from transformers import AutoModelForCausalLM, AutoTokenizer

In [ ]:
# Define a function to load the model and tokenizer
def load_model_and_tokenizer(model_name):
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForCausalLM.from_pretrained(model_name)
    return model, tokenizer

model_name2 = 'google/gemma-2-2b-it'
model2, tokenizer2 = load_model_and_tokenizer(model_name2)
model2 = model2.to('cpu')

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:
def chatbot(input_text):
    inputs = tokenizer(input_text, return_tensors="pt")
    outputs = model.generate(**inputs, max_length=300)
    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return response

In [ ]:
# Initialize a memory dictionary to hold session data
session_memory = {}

def chatbot(user_input):
    # Use a unique session key for the anonymous user
    session_key = "current_session"

    # Initialize the session memory if it doesn't exist
    if session_key not in session_memory:
        session_memory[session_key] = {"last_question": None}

    # Remember the last question
    session_memory[session_key]["last_question"] = user_input

        # Generate a response from the model
    inputs = tokenizer2(user_input, return_tensors="pt")
    inputs = inputs.to('cpu')  # Ensure inputs are on the same device as the model

    with torch.no_grad():
        outputs = model2.generate(inputs["input_ids"], max_length=150, num_return_sequences=1)

    # Decode the response
    response = tokenizer2.decode(outputs[0], skip_special_tokens=True)
    return response

In [ ]:
# Set up the Gradio interface
iface = gr.Interface(
    fn=chatbot,
    inputs=gr.Textbox(lines=2, label="Enter your ESSA question here..."),
    outputs=gr.Textbox(lines=7, label="ESSA answer"),
    title="ESSA Answers",
    description="An ESSA chatbot powered by a fine-tuned model.",
    examples=[["What is ESSA?"], ["What are the key provisions of ESSA?"]],
    allow_flagging="never",  # Disable the flagging feature
)

# Launch the interface with the image
iface.launch(share=True)

/usr/local/lib/python3.10/dist-packages/gradio/interface.py:399: UserWarning: The `allow_flagging` parameter in `Interface` is deprecated.Use `flagging_mode` instead.
  warnings.warn(

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://bc1b74957a753f3e5e.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

Processing time for simple question (What is Title I?) is about 2 minutes (117 seconds). Metrics for prompt were all well met.
Follow-up question to test memory (What does a high percentage mean?) took about 104 seconds. Unfortunately, it was not related to high poverty percentages in Title I.
Processing time for more complex question (What are consultation requirements in ESSA?) was 130 seconds. Metrics were great, but were caught off due to my defining the output @ 300 max.
Ask GW for input.