#Install all packages needed for model development

In [1]:
# Installs
!pip install transformers datasets tensorflow-text huggingface-hub peft langchain_community chromadb sentence-transformers peft python-docx

Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.44.2)
Collecting datasets
  Downloading datasets-3.1.0-py3-none-any.whl.metadata (20 kB)
Collecting tensorflow-text
  Downloading tensorflow_text-2.18.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.8 kB)
Requirement already satisfied: huggingface-hub in /usr/local/lib/python3.10/dist-packages (0.24.7)
Requirement already satisfied: peft in /usr/local/lib/python3.10/dist-packages (0.13.2)
Collecting langchain_community
  Downloading langchain_community-0.3.5-py3-none-any.whl.metadata (2.9 kB)
Collecting chromadb
  Downloading chromadb-0.5.17-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.10/dist-packages (3.2.1)
Collecting python-docx
  Downloading python_docx-1.1.2-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.16.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2024.9.11)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.4.5)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.19.1)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.66.6)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (17.0.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets) (2.2.2)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py310-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2024.9.0,>=2023.1.0 (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets)
  Downloading fsspec-2024.9.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets) (3.10.10)
Collecting tensorflow<2.19,>=2.18.0 (from tensorflow-text)
  Downloading tensorflow-2.18.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.1 kB)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub) (4.12.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from peft) (5.9.5)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.10/dist-packages (from peft) (2.5.0+cu121)
Requirement already satisfied: accelerate>=0.21.0 in /usr/local/lib/python3.10/dist-packages (from peft) (0.34.2)
Collecting SQLAlchemy<2.0.36,>=1.4 (from langchain_community)
  Downloading SQLAlchemy-2.0.35-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.6 kB)
Collecting dataclasses-json<0.7,>=0.5.7 (from langchain_community)
  Downloading dataclasses_json-0.6.7-py3-none-any.whl.metadata (25 kB)
Collecting httpx-sse<0.5.0,>=0.4.0 (from langchain_community)
  Downloading httpx_sse-0.4.0-py3-none-any.whl.metadata (9.0 kB)
Collecting langchain<0.4.0,>=0.3.6 (from langchain_community)
  Downloading langchain-0.3.7-py3-none-any.whl.metadata (7.1 kB)
Collecting langchain-core<0.4.0,>=0.3.15 (from langchain_community)
  Downloading langchain_core-0.3.15-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: langsmith<0.2.0,>=0.1.125 in /usr/local/lib/python3.10/dist-packages (from langchain_community) (0.1.137)
Collecting pydantic-settings<3.0.0,>=2.4.0 (from langchain_community)
  Downloading pydantic_settings-2.6.1-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: tenacity!=8.4.0,<10,>=8.1.0 in /usr/local/lib/python3.10/dist-packages (from langchain_community) (9.0.0)
Collecting build>=1.0.3 (from chromadb)
  Downloading build-1.2.2.post1-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: pydantic>=1.9 in /usr/local/lib/python3.10/dist-packages (from chromadb) (2.9.2)
Collecting chroma-hnswlib==0.7.6 (from chromadb)
  Downloading chroma_hnswlib-0.7.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (252 bytes)
Collecting fastapi>=0.95.2 (from chromadb)
  Downloading fastapi-0.115.4-py3-none-any.whl.metadata (27 kB)
Collecting uvicorn>=0.18.3 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading uvicorn-0.32.0-py3-none-any.whl.metadata (6.6 kB)
Collecting posthog>=2.4.0 (from chromadb)
  Downloading posthog-3.7.0-py2.py3-none-any.whl.metadata (2.0 kB)
Collecting onnxruntime>=1.14.1 (from chromadb)
  Downloading onnxruntime-1.20.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (4.4 kB)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (1.16.0)
Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0 (from chromadb)
  Downloading opentelemetry_exporter_otlp_proto_grpc-1.27.0-py3-none-any.whl.metadata (2.3 kB)
Collecting opentelemetry-instrumentation-fastapi>=0.41b0 (from chromadb)
  Downloading opentelemetry_instrumentation_fastapi-0.48b0-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (1.16.0)
Collecting pypika>=0.48.9 (from chromadb)
  Downloading PyPika-0.48.9.tar.gz (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.3/67.3 kB 4.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting overrides>=7.3.1 (from chromadb)
  Downloading overrides-7.7.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.10/dist-packages (from chromadb) (6.4.5)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (1.64.1)
Collecting bcrypt>=4.0.1 (from chromadb)
  Downloading bcrypt-4.2.0-cp39-abi3-manylinux_2_28_x86_64.whl.metadata (9.6 kB)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (0.12.5)
Collecting kubernetes>=28.1.0 (from chromadb)
  Downloading kubernetes-31.0.0-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting mmh3>=4.0.1 (from chromadb)
  Downloading mmh3-5.0.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (14 kB)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.10/dist-packages (from chromadb) (3.10.10)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (0.27.2)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.10/dist-packages (from chromadb) (13.9.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (1.5.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (1.13.1)
Requirement already satisfied: Pillow in /usr/local/lib/python3.10/dist-packages (from sentence-transformers) (10.4.0)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from python-docx) (5.3.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (2.4.3)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: yarl<2.0,>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.17.0)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (4.0.3)
Collecting pyproject_hooks (from build>=1.0.3->chromadb)
  Downloading pyproject_hooks-1.2.0-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: tomli>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from build>=1.0.3->chromadb) (2.0.2)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json<0.7,>=0.5.7->langchain_community)
  Downloading marshmallow-3.23.1-py3-none-any.whl.metadata (7.5 kB)
Collecting typing-inspect<1,>=0.4.0 (from dataclasses-json<0.7,>=0.5.7->langchain_community)
  Downloading typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Collecting starlette<0.42.0,>=0.40.0 (from fastapi>=0.95.2->chromadb)
  Downloading starlette-0.41.2-py3-none-any.whl.metadata (6.0 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.10/dist-packages (from httpx>=0.27.0->chromadb) (3.7.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx>=0.27.0->chromadb) (2024.8.30)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx>=0.27.0->chromadb) (1.0.6)
Requirement already satisfied: idna in /usr/local/lib/python3.10/dist-packages (from httpx>=0.27.0->chromadb) (3.10)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from httpx>=0.27.0->chromadb) (1.3.1)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.14.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (1.16.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (2.8.2)
Requirement already satisfied: google-auth>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (2.27.0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (1.8.0)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (1.3.1)
Requirement already satisfied: oauthlib>=3.2.2 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (3.2.2)
Requirement already satisfied: urllib3>=1.24.2 in /usr/local/lib/python3.10/dist-packages (from kubernetes>=28.1.0->chromadb) (2.2.3)
Collecting durationpy>=0.7 (from kubernetes>=28.1.0->chromadb)
  Downloading durationpy-0.9-py3-none-any.whl.metadata (338 bytes)
Requirement already satisfied: langchain-text-splitters<0.4.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from langchain<0.4.0,>=0.3.6->langchain_community) (0.3.0)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /usr/local/lib/python3.10/dist-packages (from langchain-core<0.4.0,>=0.3.15->langchain_community) (1.33)
Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from langsmith<0.2.0,>=0.1.125->langchain_community) (1.0.0)
Collecting coloredlogs (from onnxruntime>=1.14.1->chromadb)
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.10/dist-packages (from onnxruntime>=1.14.1->chromadb) (24.3.25)
Requirement already satisfied: protobuf in /usr/local/lib/python3.10/dist-packages (from onnxruntime>=1.14.1->chromadb) (3.20.3)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from onnxruntime>=1.14.1->chromadb) (1.13.1)
Requirement already satisfied: deprecated>=1.2.6 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-api>=1.2.0->chromadb) (1.2.14)
Requirement already satisfied: setuptools>=16.0 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-api>=1.2.0->chromadb) (75.1.0)
Requirement already satisfied: googleapis-common-protos~=1.52 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.65.0)
Collecting opentelemetry-exporter-otlp-proto-common==1.27.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_exporter_otlp_proto_common-1.27.0-py3-none-any.whl.metadata (1.8 kB)
Collecting opentelemetry-proto==1.27.0 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_proto-1.27.0-py3-none-any.whl.metadata (2.3 kB)
Collecting opentelemetry-sdk>=1.2.0 (from chromadb)
  Downloading opentelemetry_sdk-1.27.0-py3-none-any.whl.metadata (1.5 kB)
Collecting opentelemetry-instrumentation-asgi==0.48b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_instrumentation_asgi-0.48b0-py3-none-any.whl.metadata (2.0 kB)
Collecting opentelemetry-instrumentation==0.48b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_instrumentation-0.48b0-py3-none-any.whl.metadata (6.1 kB)
Collecting opentelemetry-semantic-conventions==0.48b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_semantic_conventions-0.48b0-py3-none-any.whl.metadata (2.4 kB)
Collecting opentelemetry-util-http==0.48b0 (from opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading opentelemetry_util_http-0.48b0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: wrapt<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from opentelemetry-instrumentation==0.48b0->opentelemetry-instrumentation-fastapi>=0.41b0->chromadb) (1.16.0)
Collecting asgiref~=3.0 (from opentelemetry-instrumentation-asgi==0.48b0->opentelemetry-instrumentation-fastapi>=0.41b0->chromadb)
  Downloading asgiref-3.8.1-py3-none-any.whl.metadata (9.3 kB)
Collecting opentelemetry-api>=1.2.0 (from chromadb)
  Downloading opentelemetry_api-1.27.0-py3-none-any.whl.metadata (1.4 kB)
Collecting importlib-metadata<=8.4.0,>=6.0 (from opentelemetry-api>=1.2.0->chromadb)
  Downloading importlib_metadata-8.4.0-py3-none-any.whl.metadata (4.7 kB)
Collecting monotonic>=1.5 (from posthog>=2.4.0->chromadb)
  Downloading monotonic-1.6-py2.py3-none-any.whl.metadata (1.5 kB)
Collecting backoff>=1.10.0 (from posthog>=2.4.0->chromadb)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic>=1.9->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in /usr/local/lib/python3.10/dist-packages (from pydantic>=1.9->chromadb) (2.23.4)
Collecting python-dotenv>=0.21.0 (from pydantic-settings<3.0.0,>=2.4.0->langchain_community)
  Downloading python_dotenv-1.0.1-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->chromadb) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->chromadb) (2.18.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from SQLAlchemy<2.0.36,>=1.4->langchain_community) (3.1.1)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text) (1.6.3)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text) (3.4.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text) (2.5.0)
Collecting tensorboard<2.19,>=2.18 (from tensorflow<2.19,>=2.18.0->tensorflow-text)
  Downloading tensorboard-2.18.0-py3-none-any.whl.metadata (1.6 kB)
Collecting keras>=3.5.0 (from tensorflow<2.19,>=2.18.0->tensorflow-text)
  Downloading keras-3.6.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text) (3.12.1)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text) (0.4.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.10/dist-packages (from tensorflow<2.19,>=2.18.0->tensorflow-text) (0.37.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.13.0->peft) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.13.0->peft) (3.1.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from sympy->onnxruntime>=1.14.1->chromadb) (1.3.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from typer>=0.9.0->chromadb) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Collecting httptools>=0.5.0 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading httptools-0.6.4-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.6 kB)
Collecting uvloop!=0.15.0,!=0.15.1,>=0.14.0 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading uvloop-0.21.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Collecting watchfiles>=0.13 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading watchfiles-0.24.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Collecting websockets>=10.4 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading websockets-13.1-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn->sentence-transformers) (3.5.0)

#Import all libraries needed for model development

In [2]:
# Libraries
import os
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
import transformers
from transformers import AutoTokenizer, AutoModelForCausalLM, Trainer, TrainingArguments
from transformers import StoppingCriteria, StoppingCriteriaList
from torch.utils.data import DataLoader, Dataset
from huggingface_hub import login
from google.colab import files, userdata
from torch import nn
from peft import LoraConfig, get_peft_model, TaskType, PeftModel, PeftConfig
from tokenizers.processors import TemplateProcessing
from docx import Document
from langchain.document_loaders import TextLoader
from langchain.text_splitter import CharacterTextSplitter
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import Chroma
from langchain.chains import RetrievalQA
from langchain.llms import HuggingFacePipeline

# Login to Hugging Face

In [3]:
# Login to Hugging Face
login(token='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')

The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `huggingface-cli` if you want to set the git credential as well.
Token is valid (permission: fineGrained).
Your token has been saved to /root/.cache/huggingface/token
Login successful

# Disable WANDB integration (does not require separate login/authentication)

In [4]:
# Disable WANDB integration
os.environ["WANDB_DISABLED"] = "true"

# Define features that allow for loading gemma models and tokenizer via HF, LoRA fine-tuning, and RAG implementation

In [5]:
# Load model and tokenizer via HF
def load_model_and_tokenizer(model_name):
    model = AutoModelForCausalLM.from_pretrained(model_name, attn_implementation='eager')
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    return model, tokenizer

# Load tokenizer for fine-tune data
def load_tokenizer_for_ft(model_name):
    tokenizer = AutoTokenizer.from_pretrained(model_name, add_eos_token=True)
    return tokenizer

# A class to make sure we stop when the EOS token is generated
class StoppingCriteriaSub(StoppingCriteria):
    def __init__(self, stop_id = 1):
      StoppingCriteria.__init__(self),
    def __call__(self, input_ids: torch.LongTensor, scores: torch.FloatTensor, stop_id = 1):
      if stop_id in input_ids:
        # print("FOUND STOP_ID:", input_ids)
        return True
      else:
        return False

# Generate set-up for model response
def generate_response(prompt, device='cpu'):
    # debug - print("input_ids=", encoding.input_ids)
    encoding = tokenizer(prompt, return_tensors='pt').to(device)
    generation_config = model.generation_config
    generation_config.max_new_tokens = 512
    generation_config.temperature = 0.7
    #generation_config.top_p = 0.7 # uncomment for more 'creative' completion
    generation_config.num_return_sequences = 1

    # this will ensure text generation stops at the EOS token
    stopping_criteria = StoppingCriteriaList([StoppingCriteriaSub(stop_id = tokenizer.eos_token_id)  ])
    completion = model.generate(input_ids = encoding.input_ids,
                                attention_mask = encoding.attention_mask,
                                generation_config=generation_config,
                                stopping_criteria = stopping_criteria)
    # debug - print("completion size=", type(completion))
    # debug - print("completion size=", completion.shape)
    # debug - print("completion=", completion)
    response = tokenizer.decode(completion[0], skip_special_tokens=True)
    return response.replace(prompt, "")

# Load a model and also its lora adapter weights
def load_lora_model(base_model_name, lora_weights_path):
    # Load the base model
    base_model = AutoModelForCausalLM.from_pretrained(base_model_name, attn_implementation='eager')

    # Load the LoRA configuration
    peft_config = PeftConfig.from_pretrained(lora_weights_path)

    # Load the LoRA model
    model = PeftModel.from_pretrained(base_model, lora_weights_path)

    # Merge LoRA weights with base model
    model = model.merge_and_unload()

    # Load the tokenizer
    tokenizer = AutoTokenizer.from_pretrained(base_model_name)

    return model, tokenizer

# Useful in our RAG implementation
class DocumentWithText:
    def __init__(self, content, metadata=None):
        self.page_content = content
        self.metadata = metadata if metadata is not None else {}

# Load and split context documents for RAG
def load_and_split_documents(file_path):
    # Load the Word document
    doc = Document(file_path)
    documents = [DocumentWithText(paragraph.text) for paragraph in doc.paragraphs if paragraph.text]

    # Here you can choose how to split the text
    text_splitter = CharacterTextSplitter(chunk_size=9000, chunk_overlap=0)
    texts = text_splitter.split_documents(documents)
    return texts

# Upload my dataset

In [12]:
uploaded = files.upload()

Saving ESSA q and a_10.31.csv to ESSA q and a_10.31.csv

# Define how to handle user prompt display

In [6]:
# Initialize prompt display
def display_chat(prompt, response):
    print("Prompt:")
    print(prompt)
    print("-------------------------------------------")
    print("\nResponse:")
    print(response)

# Load the gemma-2-2b model (base model)

In [7]:
model_name = 'google/gemma-2-2b'
model, tokenizer = load_model_and_tokenizer(model_name)
model = model.to('cpu')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/818 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/24.2k [00:00<?, ?B/s]

Downloading shards:   0%|          | 0/3 [00:00<?, ?it/s]

model-00001-of-00003.safetensors:   0%|          | 0.00/4.99G [00:00<?, ?B/s]

model-00002-of-00003.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

model-00003-of-00003.safetensors:   0%|          | 0.00/481M [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/168 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/46.4k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.24M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/636 [00:00<?, ?B/s]

# First test prompt: using gemma-2-2b model

In [8]:
# Define the prompt template
template = "{pre}\n\nQuestion:\n{question}"

# Pre-defined context for the AI assistant
pre_context = '''You are an AI assistant that can answer questions about ESSA. '''\
               '''ESSA stands for the Every Student Succeeds Act.'''

# List of questions to ask
questions = [
    "What is ESSA?",
    "How does ESSA impact student achievement?"
]

# Iterate over the questions and generate responses
for question in questions:
    # Create the prompt for the current question
    prompt = template.format(pre=pre_context, question=question)

    # Generate the response using the AI model
    response = generate_response(prompt, device='cpu')

    # Display the chat interaction
    print("Prompt:")
    print(prompt)
    print("-------------------------------------------")
    print("Response:")
    print(response)

/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.7` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(

Prompt:
You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act.

Question:
What is ESSA?
-------------------------------------------
Response:


Answer:
ESSA is a federal law that replaced No Child Left Behind. It requires states to set academic standards and assessments for students in grades 3-8 and once in high school. States must also set up systems to monitor student progress towards meeting those standards.

Question:
What are the main goals of ESSA?

Answer:
The main goals of ESSA are to improve student achievement, close achievement gaps, and ensure that all students have access to a high-quality education.

Question:
What are some of the key provisions of ESSA?

Answer:
Some of the key provisions of ESSA include:

-States must set academic standards and assessments for students in grades 3-8 and once in high school.

-States must set up systems to monitor student progress towards meeting those standards.

-States must provide all students with access to a high-quality education.

Question:
What are some of the challenges facing ESSA?

Answer:
Some of the challenges facing ESSA include:

-States may not have the resources to implement ESSA effectively.

-States may not have the capacity to monitor student progress towards meeting academic standards.

-States may not have the resources to provide all students with access to a high-quality education.

Question:
What are some of the benefits of ESSA?

Answer:
Some of the benefits of ESSA include:

-ESSA provides states with more flexibility in how they implement the law.

-ESSA provides states with more resources to implement the law.

-ESSA provides states with more capacity to monitor student progress towards meeting academic standards.

Question:
What are some of the criticisms of ESSA?

Answer:
Some of the criticisms of ESSA include:

-ESSA does not provide enough resources to states to implement the law effectively.

-ESSA does not provide enough capacity to states to monitor student progress towards meeting academic standards.

-ESSA does not provide enough resources to states to provide all students with access to a high-quality education.

Question:
What are some of the ways that ESSA can be improved?

Answer:
Some of the ways that ESSA can be improved include:

-Providing more resources to states to implement the law effectively.

-Providing more capacity to states to monitor student progress towards meeting academic standards.

-Providing more resources to states to provide all students with access to a high-quality education.

Question:
What are some of the
Prompt:
You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act.

Question:
How does ESSA impact student achievement?
-------------------------------------------
Response:


Answer:
ESSA is a federal law that sets the standards for education in the United States. It requires states to develop and implement plans to improve student achievement. ESSA also provides funding for schools and districts to implement these plans.

Question:
What are some of the key provisions of ESSA?

Answer:
ESSA has several key provisions, including:

- Requiring states to develop and implement plans to improve student achievement.
- Providing funding for schools and districts to implement these plans.
- Requiring states to report on student achievement and progress.
- Providing flexibility for states to tailor their plans to meet the needs of their students.

Question:
How does ESSA impact the education system in the United States?

Answer:
ESSA has had a significant impact on the education system in the United States. It has provided states with more flexibility to tailor their plans to meet the needs of their students. It has also provided funding for schools and districts to implement these plans.

Question:
What are some of the challenges that ESSA faces?

Answer:
ESSA faces several challenges, including:

- Ensuring that all students have access to a high-quality education.
- Ensuring that all students are prepared for college and career.
- Ensuring that all students are engaged in learning.
- Ensuring that all students are safe and secure in their schools.

Question:
How can ESSA be improved?

Answer:
ESSA can be improved by:

- Ensuring that all students have access to a high-quality education.
- Ensuring that all students are prepared for college and career.
- Ensuring that all students are engaged in learning.
- Ensuring that all students are safe and secure in their schools.

Question:
What are some of the benefits of ESSA?

Answer:
ESSA has several benefits, including:

- Providing states with more flexibility to tailor their plans to meet the needs of their students.
- Providing funding for schools and districts to implement these plans.
- Requiring states to report on student achievement and progress.
- Providing flexibility for states to tailor their plans to meet the needs of their students.

Question:
What are some of the challenges that ESSA faces?

Answer:
ESSA faces several challenges, including:

- Ensuring that all students have access to a high-quality education.
- Ensuring that all students are prepared for college and career.
- Ensuring that all students are engaged in learning.
- Ensuring that

Evaluation of prompt 1: More info than requested, but info is correct. Tone is good.

# Load second model, the gemma-2-2b-it

In [10]:
model_name = 'google/gemma-2-2b-it'
model, tokenizer = load_model_and_tokenizer(model_name)
model = model.to('cpu')

config.json:   0%|          | 0.00/838 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/24.2k [00:00<?, ?B/s]

Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/4.99G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/241M [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/187 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/47.0k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/4.24M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.5M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/636 [00:00<?, ?B/s]

# Second test prompt: using gemma-2-2b-it model

In [11]:
# Define the second prompt template
template = "{pre}\n\nQuestion:\n{question}"

# Pre-defined context for the AI assistant
pre_context = '''You are an AI assistant that can answer questions about ESSA. '''\
               '''ESSA stands for the Every Student Succeeds Act.'''

# List of questions to ask
questions = [
    "What is ESSA?",
    "How does ESSA impact student achievement?"
]

# Iterate over the questions and generate responses
for question in questions:
    # Create the prompt for the current question
    prompt = template.format(pre=pre_context, question=question)

    # Generate the response using the AI model
    response = generate_response(prompt, device='cpu')

    # Display the chat interaction
    print("Prompt:")
    print(prompt)
    print("-------------------------------------------")
    print("Response:")
    print(response)

Prompt:
You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act.

Question:
What is ESSA?
-------------------------------------------
Response:


Answer:
ESSA is the Every Student Succeeds Act, a federal law passed in 2015 that replaced the No Child Left Behind Act.

Here are some key features of ESSA:

* **Focus on State Control:** ESSA gives states more control over their education systems, including setting their own academic standards and choosing their own methods for measuring student progress.
* **Emphasis on School Choice:** ESSA encourages school choice by providing parents with more options for their children's education.
* **Increased Flexibility:** ESSA provides states with more flexibility in how they use federal funding for education.
* **Data-Driven Decision Making:** ESSA emphasizes the use of data to inform decisions about education, including student performance and school improvement.
* **Support for Students with Disabilities:** ESSA ensures that students with disabilities have access to appropriate supports and services.
* **Teacher Quality:** ESSA promotes teacher quality by providing states with resources to support teacher development and recruitment.


Let me know if you have any other questions about ESSA.

Prompt:
You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act.

Question:
How does ESSA impact student achievement?
-------------------------------------------
Response:


Answer:
The Every Student Succeeds Act (ESSA) aims to improve student achievement by providing states with more flexibility and control over their education systems.

Here's how ESSA impacts student achievement:

**Increased Flexibility:**
* **State-led accountability systems:** ESSA gives states the authority to design their own accountability systems, tailored to their specific needs and priorities. This allows states to focus on what works best for their students and communities.
* **Flexibility in using federal funds:** States can use federal funding for a wider range of purposes, including supporting early childhood education, providing targeted interventions for struggling students, and improving teacher quality.

**Focus on Evidence-Based Practices:**
* **Emphasis on data-driven decision-making:** ESSA encourages states to use data to inform their decisions about student achievement, including identifying areas where students need additional support.
* **Support for evidence-based interventions:** States can use federal funds to implement evidence-based interventions, such as early literacy programs and math interventions, to improve student outcomes.

**Support for School Choice:**
* **Increased options for parents:** ESSA allows parents to choose the best educational environment for their children, including charter schools, magnet schools, and other public school options.

**Other Key Impacts:**
* **Focus on closing achievement gaps:** ESSA emphasizes the importance of addressing disparities in student achievement based on race, ethnicity, gender, and other factors.
* **Emphasis on early childhood education:** ESSA recognizes the importance of early childhood education and provides funding for programs that support children's development.

**Overall, ESSA aims to create a more equitable and effective education system that supports all students in achieving their full potential.**


**Note:** It's important to remember that ESSA is a complex law with many nuances. The specific impacts of ESSA on student achievement can vary depending on the state and the implementation of the law.

Evaluation of prompt 2: Answers both questions very well! Info is correct and clear. Tone is good.

# Re-upload and define my dataset for fine-tuning

In [38]:
import pandas as pd
from transformers import AutoTokenizer, Trainer, TrainingArguments, DataCollatorForLanguageModeling
from peft import LoraConfig, get_peft_model, TaskType
import os

In [39]:
# Load dataset
df = pd.read_csv('ESSA q and a_10.31.csv')
from sklearn.model_selection import train_test_split
train_df, val_df = train_test_split(df, test_size=0.2, random_state=42)

In [42]:
# Define format of the fine-tuning data
template = "{pre}\n\nContext:\n{context}\n\nQuestion:\n{question}\n\nAnswer:\n{answer}\n\nSource:\n{source}"

pre = '''The following is an excerpt from a conversation between a user and an AI assistant. '''\
      '''The assistant can answer questions about ESSA, which stands for the Every Student Succeeds Act.'''

# Format each training string, put them all into a list
ft_all_data = []
for idx, row in train_df.iterrows():
    ft_item = template.format(
        pre=pre,
        context=row['Context'],  # Make sure you include this if you have a context column
        question=row['Question'],
        answer=row['Answer'],
        source=row.get('Source', '')  # Safely get the source, default to empty string if not found
    )
    ft_all_data.append(ft_item)

# Tokenize all the fine-tune data
tokenizer = AutoTokenizer.from_pretrained("google/gemma-2-2b-it")
tokenized_ft_data = []
for el in ft_all_data:
    tok_item = tokenizer(el, padding=True, truncation=True)
    tokenized_ft_data.append(tok_item)

# Check for BOS and EOS tokens
print("bos=", tokenizer.bos_token_id, "eos=", tokenizer.eos_token_id)
print("----tokenized----")
print(tokenized_ft_data[0])

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

bos= 2 eos= 1
----tokenized----
{'input_ids': [2, 651, 2412, 603, 671, 80545, 774, 476, 12836, 1865, 476, 2425, 578, 671, 16481, 20409, 235265, 714, 20409, 798, 3448, 3920, 1105, 62639, 235280, 235269, 948, 12353, 604, 573, 7205, 13137, 64795, 17825, 5031, 235265, 109, 2930, 235292, 108, 192075, 109, 9413, 235292, 108, 2299, 1721, 62639, 235280, 8964, 10522, 235336, 109, 1261, 235292, 108, 192075, 35867, 573, 1307, 8072, 22280, 45598, 43900, 674, 10522, 2004, 614, 664, 114089, 19767, 2776, 236338, 109, 3154, 235292, 108, 12583, 16481], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

## Fine-tune using LoRA, 2 epochs

In [43]:
from transformers import DataCollatorForLanguageModeling

In [44]:
# Load the model
model_name = 'google/gemma-2-2b-it'
model, tokenizer = load_model_and_tokenizer(model_name)
model = model.to('cpu')

# Setup LoRA configuration
peft_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    inference_mode=False,
    r=6  # Adjust based on your experimental needs
)
model = get_peft_model(model, peft_config)

# Define Trainer arguments
training_args = TrainingArguments(
    output_dir="/content/drive/MyDrive/Kaggle_X/Mary_ESSA/output/gemma2_essa_ft1",
    learning_rate=1e-4,  # Experiment with lower learning rates
    per_device_train_batch_size=2,  # Increase batch size if possible
    num_train_epochs=2,  # Experiment with the number of epochs
    weight_decay=0.01,  # Introduce weight decay
    logging_steps=100,
    evaluation_strategy="steps",  # Evaluate periodically
)

# Initialize Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ft_data,
    data_collator=DataCollatorForLanguageModeling(tokenizer, mlm=False),
)

# Disable cache during training
model.config.use_cache = False
trainer.train()

# Save the fine-tuned model and tokenizer
model.save_pretrained("/content/drive/MyDrive/Kaggle_X/Mary_ESSA/output/gemma2_essa_ft1")
tokenizer.save_pretrained("/content/drive/MyDrive/Kaggle_X/Mary_ESSA/output/gemma2_essa_ft1")

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

/usr/local/lib/python3.10/dist-packages/transformers/training_args.py:1525: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

('/content/drive/MyDrive/Kaggle_X/Mary_ESSA/output/gemma2_essa_ft1/tokenizer_config.json',
 '/content/drive/MyDrive/Kaggle_X/Mary_ESSA/output/gemma2_essa_ft1/special_tokens_map.json',
 '/content/drive/MyDrive/Kaggle_X/Mary_ESSA/output/gemma2_essa_ft1/tokenizer.model',
 '/content/drive/MyDrive/Kaggle_X/Mary_ESSA/output/gemma2_essa_ft1/added_tokens.json',
 '/content/drive/MyDrive/Kaggle_X/Mary_ESSA/output/gemma2_essa_ft1/tokenizer.json')

In [45]:
# Define the directory name
new_dir = "/KaggleX/MWhite"

# Create the directory
os

Evaluate model tomorrow

In [ ]:
#Try this tomorrow instead of tonight, please
# Evaluation: Prepare validation data in the same way
val_all_data = []
for idx, row in val_df.iterrows():
    val_item = template.format(
        pre=pre,
        context=row['Context'],
        question=row['Question'],
        answer=row['Answer'],
        source=row['Source']
    )
    val_all_data.append(val_item)

# Tokenize validation data
tokenized_val_data = []
for el in val_all_data:
    tok_item = tokenizer(el, padding=True, truncation=True, return_tensors='pt')
    tokenized_val_data.append(tok_item)

# Evaluate the model on the validation dataset
# Create a custom evaluation function
def evaluate_model(trainer, tokenized_val_data):
    # You can create a DataLoader for the validation dataset
    val_dataset = torch.utils.data.TensorDataset(*tokenized_val_data)
    trainer.evaluate(val_dataset)

# Run the evaluation
evaluate_model(trainer, tokenized_val_data)

# Third test prompt: using LoRA fine-tuned model, 2 epochs

In [47]:
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

# Load the fine-tuned model and tokenizer
model_path = "/content/drive/MyDrive/Kaggle_X/Mary_ESSA/output/gemma2_essa_ft1"
model = AutoModelForCausalLM.from_pretrained(model_path)
tokenizer = AutoTokenizer.from_pretrained(model_path)

# Set the model to evaluation mode
model.eval()

# Define the initial context/preamble
pre_context = "You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act."

# Function to generate a response for a given prompt
def generate_response(prompt):
    # Tokenize the input prompt
    inputs = tokenizer(prompt, return_tensors="pt")

    # Generate a response
    with torch.no_grad():
        outputs = model.generate(inputs["input_ids"], max_length=150, num_return_sequences=1)

    # Decode the generated response
    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return response

# Ask the first question
first_question = f"{pre_context}\n\nWhat is ESSA?"
response_1 = generate_response(first_question)
print("Question 1:", first_question)
print("Response 1:", response_1)

# Scond question
second_question = "How does ESSA impact student achievement?"
response_2 = generate_response(second_question)
print("\nQuestion 2:", second_question)
print("Response 2:", response_2)

# Third question
third_question = "What is Title I?"
response_3 = generate_response(third_question)
print("\nQuestion 3:", third_question)
print("Response 3:", response_3)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Question 1: You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act.

What is ESSA?
Response 1: You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act.

What is ESSA?

ESSA is a federal law that was passed in 2015. It replaced the No Child Left Behind Act (NCLB).

What are the main goals of ESSA?

The main goals of ESSA are to:

* **Improve student achievement:** ESSA aims to ensure that all students, regardless of their background, have the opportunity to succeed in school.
* **Increase accountability:** ESSA requires states to set high standards for student achievement and to hold schools accountable for meeting those standards.
* **Promote flexibility:** ESSA gives states more flexibility in how

Question 2: How does ESSA impact student achievement?
Response 2: How does ESSA impact student achievement?

The Every Student Succeeds Act (ESSA) has had a significant impact on student achievement, but its effects are complex and multifaceted. Here's a breakdown of its key impacts:

**Positive Impacts:**

* **Increased Flexibility:** ESSA provides states with more flexibility in designing their own education systems, allowing them to tailor programs to their specific needs and resources. This has led to the development of innovative approaches to teaching and learning, such as personalized learning, project-based learning, and STEM education.
* **Focus on Data-Driven Decision Making:** ESSA emphasizes the use of data to inform decision-making at all levels of education. This has led to a greater focus on student achievement

Question 3: What is Title I?
Response 3: What is Title I?

Title I of the Elementary and Secondary Education Act of 1965 is a federal program that provides financial assistance to schools with a high percentage of low-income students. The program is designed to help schools meet the educational needs of these students and to close the achievement gap between low-income students and their more affluent peers.

Here's a breakdown of Title I:

**Purpose:**

* To ensure that all children have access to a high-quality education, regardless of their family's income.
* To provide additional resources to schools with high concentrations of low-income students.
* To help schools improve the academic performance of their students.

**Funding:**

* Title I funds

Evaluation of LoRA results, looks good. Can even capture Title I which wasn't totally in my dataset.

## Fine-tune using LoRA, 25 epochs

In [ ]:
#I will try this later tonight or tomorrow
# Load your dataset
df = pd.read_csv('ESSA q and a_10.31.csv')
from sklearn.model_selection import train_test_split
train_df, val_df = train_test_split(df, test_size=0.2, random_state=42)

# Define format of the fine-tuning data
template = "{pre}\n\nContext:\n{context}\n\nQuestion:\n{question}\n\nAnswer:\n{answer}\n\nSource:\n{source}"

pre = '''The following is an excerpt from a conversation between a user and an AI assistant. '''\
      '''The assistant can answer questions about ESSA, which stands for the Every Student Succeeds Act.'''

# Format each training string, put them all into a list
ft_all_data = []
for idx, row in traindf.iterrows():
    ft_item = template.format(
        pre=pre,
        context=row['Context'],
        question=row['Question'],
        answer=row['Answer'],
        source=row['Source']
    )
    ft_all_data.append(ft_item)

# Tokenize all the fine-tune data
tokenizer = AutoTokenizer.from_pretrained("google/gemma-2-2b-it")
tokenized_ft_data = tokenizer(ft_all_data, padding=True, truncation=True, return_tensors="pt")

# Load model
model_name = 'google/gemma-2-2b-it'
model = AutoModelForCausalLM.from_pretrained(model_name)
model = model.to('cpu')

# Define LoRA configuration
from peft import LoraConfig, TaskType, get_peft_model

peft_config = LoraConfig(
  task_type=TaskType.CAUSAL_LM,
  inference_mode=False,
  r=6  # Match your experimental needs
)

# Prepare training arguments
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir="/content/drive/MyDrive/Kaggle_X/Mary_ESSA/output/gemma2_essa_ft1",
    learning_rate=1e-4,  # Experiment with lower learning rates
    per_device_train_batch_size=2,  # Increase batch size if possible
    num_train_epochs=25,  # Set to 25 or 30 as needed
    weight_decay=0.01,  # Introduce weight decay
    logging_steps=100,
    evaluation_strategy="steps",  # Evaluate periodically
)

# Initialize the Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_ft_data,
    data_collator=DataCollatorForLanguageModeling(tokenizer, mlm=False),
)

# Disable cache during training
model.config.use_cache = False

# Start training
trainer.train()

# Save the fine-tuned model and tokenizer
model.save_pretrained("/content/drive/MyDrive/Kaggle_X/Mary_ESSA/output/gemma2_essa_ft1")
tokenizer.save_pretrained("/content/drive/MyDrive/Kaggle_X/Mary_ESSA/output/gemma2_essa_ft1")

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).

trainable params: 798,720 || all params: 2,615,140,608 || trainable%: 0.0305

TrainOutput(global_step=25, training_loss=1.5811524391174316, metrics={'train_runtime': 131.3054, 'train_samples_per_second': 0.19, 'train_steps_per_second': 0.19, 'total_flos': 26430381734400.0, 'train_loss': 1.5811524391174316, 'epoch': 25.0})

Try the 25 tomorrow along with the eval_df test

In [ ]:
#Don't save it unless it works/ Save the fine-tuned model
lora_save_path = "/content/drive/MyDrive/Kaggle_X/Mary_ESSA/output/gemma2_LoRA/fine_tuned_model"
os.makedirs(os.path.dirname(lora_save_path), exist_ok=True)
model.save_pretrained(lora_save_path)

In [ ]:
# With Gemma2 base 2b-it, the function loads and merges the LORA adapter weights.
model, tokenizer = load_lora_model("google/gemma-2-2b-it", lora_save_path)
model = model.to('cpu')

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

#RAG implementation

# Install additional RAG libraries and tools

In [48]:
!pip install python-docx langchain

Requirement already satisfied: python-docx in /usr/local/lib/python3.10/dist-packages (1.1.2)
Requirement already satisfied: langchain in /usr/local/lib/python3.10/dist-packages (0.3.7)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from python-docx) (5.3.0)
Requirement already satisfied: typing-extensions>=4.9.0 in /usr/local/lib/python3.10/dist-packages (from python-docx) (4.12.2)
Requirement already satisfied: PyYAML>=5.3 in /usr/local/lib/python3.10/dist-packages (from langchain) (6.0.2)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /usr/local/lib/python3.10/dist-packages (from langchain) (2.0.35)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.10/dist-packages (from langchain) (3.10.10)
Requirement already satisfied: async-timeout<5.0.0,>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from langchain) (4.0.3)
Requirement already satisfied: langchain-core<0.4.0,>=0.3.15 in /usr/local/lib/python3.10/dist-packages (from langchain) (0.3.15)
Requirement already satisfied: langchain-text-splitters<0.4.0,>=0.3.0 in /usr/local/lib/python3.10/dist-packages (from langchain) (0.3.0)
Requirement already satisfied: langsmith<0.2.0,>=0.1.17 in /usr/local/lib/python3.10/dist-packages (from langchain) (0.1.137)
Requirement already satisfied: numpy<2,>=1 in /usr/local/lib/python3.10/dist-packages (from langchain) (1.26.4)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.10/dist-packages (from langchain) (2.9.2)
Requirement already satisfied: requests<3,>=2 in /usr/local/lib/python3.10/dist-packages (from langchain) (2.32.3)
Requirement already satisfied: tenacity!=8.4.0,<10,>=8.1.0 in /usr/local/lib/python3.10/dist-packages (from langchain) (9.0.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (2.4.3)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (6.1.0)
Requirement already satisfied: yarl<2.0,>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain) (1.17.0)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /usr/local/lib/python3.10/dist-packages (from langchain-core<0.4.0,>=0.3.15->langchain) (1.33)
Requirement already satisfied: packaging<25,>=23.2 in /usr/local/lib/python3.10/dist-packages (from langchain-core<0.4.0,>=0.3.15->langchain) (24.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from langsmith<0.2.0,>=0.1.17->langchain) (0.27.2)
Requirement already satisfied: orjson<4.0.0,>=3.9.14 in /usr/local/lib/python3.10/dist-packages (from langsmith<0.2.0,>=0.1.17->langchain) (3.10.10)
Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from langsmith<0.2.0,>=0.1.17->langchain) (1.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in /usr/local/lib/python3.10/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.23.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3,>=2->langchain) (2024.8.30)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from SQLAlchemy<3,>=1.4->langchain) (3.1.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain) (3.7.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain) (1.0.6)
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain) (1.3.1)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain) (0.14.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.10/dist-packages (from jsonpatch<2.0,>=1.33->langchain-core<0.4.0,>=0.3.15->langchain) (3.0.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from yarl<2.0,>=1.12.0->aiohttp<4.0.0,>=3.8.3->langchain) (0.2.0)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio->httpx<1,>=0.23.0->langsmith<0.2.0,>=0.1.17->langchain) (1.2.2)

In [49]:
import langchain
import pandas as pd

In [50]:
from langchain.schema import Document as LangchainDocument
from langchain.text_splitter import CharacterTextSplitter
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import Chroma
from transformers import pipeline

In [51]:
pip install pandas openpyxl

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (3.1.5)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

# Import and manage RAG file

In [52]:
uploaded = files.upload()

Saving ESSA RAG file_10.31.xlsx to ESSA RAG file_10.31.xlsx

In [53]:
# Load the Excel file
xls_file = "ESSA RAG file_10.31.xlsx"

# Read the entire Excel file
df2 = pd.read_excel(xls_file)

# Specify column names
context_column = 'Context'
question_column = 'Question'
answer_column = 'Answer'
audience_column = 'Potential_audience'
source_column = 'Source'

# Create a list to hold Langchain Document objects
documents = []

# Iterate through each row in the DataFrame and format the text
for idx, row in df2.iterrows():
    context = row[context_column] if pd.notna(row[context_column]) else ''
    question = row[question_column] if pd.notna(row[question_column]) else ''
    answer = row[answer_column] if pd.notna(row[answer_column]) else ''
    audience = row[audience_column] if pd.notna(row[audience_column]) else ''
    source = row[source_column] if pd.notna(row[source_column]) else ''

    # Create combined content for the Langchain Document
    combined_content = (
        f"Context: {context}\n"
        f"Question: {question}\n"
        f"Answer: {answer}\n"
        f"Potential Audience: {audience}\n"
        f"Source: {source}\n"
    )

    # Create a Langchain Document object
    documents.append(LangchainDocument(page_content=combined_content))

# Check if data has been populated
if not documents:
    raise ValueError("No documents were created. Check your DataFrame for data.")

# Create embeddings and vector store
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
db = Chroma.from_documents(documents, embeddings)

# Create a retriever from the vector database
retriever = db.as_retriever(search_type="similarity_score_threshold", search_kwargs={"k": 5, "score_threshold": 0.3})

<ipython-input-53-00b373271c5c>:37: LangChainDeprecationWarning: The class `HuggingFaceEmbeddings` was deprecated in LangChain 0.2.2 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFaceEmbeddings``.
  embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

# Develop and deploy RAG implementation

In [55]:
# Load a separate QA pipeline
qa_pipeline = pipeline("question-answering", model="distilbert-base-uncased-distilled-squad")

# Function to get answer from the model using relevant context
def get_answer(query):
    # Use the retriever to find relevant documents
    relevant_docs = retriever.get_relevant_documents(query)  # Changed invoke to retrieve

    if not relevant_docs:
        return "No relevant context found for answering the question."

    # Combine the text from relevant documents to create a coherent context
    context_chunk = "\n".join([doc.page_content for doc in relevant_docs])

    # Use the QA pipeline to get an answer
    response = qa_pipeline(question=query, context=context_chunk)

    # Return the answer found by the QA model
    return response['answer']

    # Example usage of the function
query = "What is ESSA?"
result = get_answer(query)
print("Answer:", result)

<ipython-input-55-5aae9cc5897e>:7: LangChainDeprecationWarning: The method `BaseRetriever.get_relevant_documents` was deprecated in langchain-core 0.1.46 and will be removed in 1.0. Use :meth:`~invoke` instead.
  relevant_docs = retriever.get_relevant_documents(query)  # Changed invoke to retrieve

Answer: What is the state's role in ESSA

In [56]:
# Ssecond question
query2 = "What is Title I?"
result2 = get_answer(query2)

# Result for the second question
print("Second Question:", query2)
print("Answer:", result2)

Second Question: What is Title I?
Answer: a provision of the Elementary and Secondary Education Act

In [57]:
# Third question
query3 = "What does ESSA say about state assessments?"
result3 = get_answer(query3)

# Result for the second question
print("Third Question:", query3)
print("Answer:", result3)

Third Question: What does ESSA say about state assessments?
Answer: State assessments must be designed to be valid and accessible for use by all students

RAG results are short and not very elaborate or clear.

## Everything below here is old and doesn't need review, except the Gradio code is at the very end

In [ ]:
#This below is all old, don't use

    # Create embeddings and vector store
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

# Create a Chroma vector database from the documents
db = Chroma.from_documents(data, embeddings)  # Pass the list of Document objects

# Create a retriever from the vector database
retriever = db.as_retriever(search_type="similarity_score_threshold", search_kwargs={"k": 5, "score_threshold": 0.3})

# Load the question-answering pipeline
qa_pipeline = pipeline("question-answering", model="distilbert-base-uncased-distilled-squad")

# Function to get answer from the model using relevant context
def get_answer(query):
    # Use the retriever to find relevant documents
    relevant_docs = retriever.invoke(query)  # Retrieve relevant documents for the query

    if not relevant_docs:
        return "No relevant context found for answering the question."

    # Combine the text from relevant documents to create a coherent context
    context_chunk = "\n".join([doc.page_content for doc in relevant_docs])  # Create context from retrieved documents

    # Use the QA pipeline to get an answer
    response = qa_pipeline(question=query, context=context_chunk)

    # Return the answer found by the QA model
    return response['answer']

# Example usage
query = "What is ESSA?"
result = get_answer(query)

# Display the result
print("Answer:", result)

NameError: name 'data' is not defined

In [ ]:
prompt = template.format(pre='''You are an AI assistant that can answer questions about ESSA.'''
                            ''' ESSA stands for the Every Student Succeeds Act.''',
                         question='What is ESSA?',
                         answer='')
response = generate_response(prompt)
display_chat(prompt, response)

/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.7` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(

Prompt:
You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act.

Question:
What is ESSA?

Answer:

-------------------------------------------

Response:
ESSA is the Every Student Succeeds Act, a federal law passed in 2015 that replaced the No Child Left Behind Act. ESSA aims to improve educational outcomes for all students by providing states with more flexibility and control over their education systems.

Here are some key features of ESSA:

* **Focus on accountability:** ESSA emphasizes accountability for student achievement, but it does so in a more nuanced way than NCLB. It allows states to tailor their accountability systems to meet their specific needs and priorities.
* **Emphasis on flexibility:** ESSA grants states more flexibility in designing their own curriculum, assessments, and interventions. This allows states to tailor their approach to meet the unique needs of their students and communities.
* **Increased focus on early childhood education:** ESSA recognizes the importance of early childhood education and provides funding for programs that support children's development.
* **Support for English language learners and students with disabilities:** ESSA provides resources and support for students who need additional assistance to succeed in school.
* **Data-driven decision making:** ESSA encourages states to use data to inform their decisions about education policy and practice.

In summary, ESSA is a comprehensive law that aims to improve educational outcomes for all students by providing states with more flexibility and control over their education systems.

In [ ]:
# Save the fine-tuned model
lora_save_path = "/content/drive/MyDrive/Kaggle_X/Mary_ESSA/output/gemma2_LoRA/fine_tuned_model"
os.makedirs(os.path.dirname(lora_save_path), exist_ok=True)
model.save_pretrained(lora_save_path)

In [ ]:
# With Gemma2 base 2b-it, the function loads and merges the LORA adapter weights.
model, tokenizer = load_lora_model("google/gemma-2-2b-it", lora_save_path)
model = model.to('cpu')

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

In [ ]:
uploaded = files.upload()

Saving ESSA RAG file_10.23.docx to ESSA RAG file_10.23.docx

In [ ]:
file_path = 'ESSA RAG file_10.23.docx'

In [ ]:
import langchain
print(langchain.__version__)

0.3.6

In [ ]:
from docx import Document  # Import python-docx for .docx files
from langchain.text_splitter import CharacterTextSplitter
from langchain.schema import Document as LangchainDocument

# Load the long document
doc = Document("ESSA RAG file_10.23.docx")  # Load the .docx file

# Extract text from paragraphs
text = "\n".join([paragraph.text for paragraph in doc.paragraphs if paragraph.text])

# Create Langchain Document objects
document = [LangchainDocument(page_content=text)]  # Create a list of Langchain Document

# Initialize the text splitter
text_splitter = CharacterTextSplitter(chunk_size=512, chunk_overlap=50)  # Adjust chunk_size and chunk_overlap as needed

# Split the document into manageable chunks
chunks = text_splitter.split_documents(document)

In [ ]:
import pandas as pd
from docx import Document as DocxDocument
from langchain.schema import Document  # Ensure you're using the correct Document class
from langchain.embeddings import HuggingFaceEmbeddings  # Import from langchain
from langchain.vectorstores import Chroma  # Import Chroma
from chromadb import Client  # Correct import for Chroma client
from transformers import pipeline

# Load your data into a DataFrame
doc = DocxDocument('ESSA RAG file_10.23.docx')

# Extract text from the document and convert it to a list of Document objects
data = []
for paragraph in doc.paragraphs:
    data.append(Document(page_content=paragraph.text))  # Use the correct argument

# Create embeddings and vector store
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

# Create a Chroma vector database from the documents
try:
    db.delete_collection()  # Attempt to delete existing collection
except Exception as e:
    print(f"Could not delete collection: {e}")

# Create a Chroma vector database from the list of documents
db = Chroma.from_documents(data, embeddings)  # Pass the list of Document objects

# Create a retriever from the vector database
retriever = db.as_retriever(search_type="similarity_score_threshold", search_kwargs={"k": 5, "score_threshold": 0.3})

# Load the question-answering pipeline
qa_pipeline = pipeline("question-answering", model="distilbert-base-uncased-distilled-squad")

# Function to get answer from the model using relevant context
def get_answer(query):
    # Use the retriever to find relevant documents
    relevant_docs = retriever.invoke(query)  # Retrieve relevant documents for the query

    if not relevant_docs:
        return "No relevant context found for answering the question."

    # Combine the text from relevant documents to create a coherent context
    context_chunk = "\n".join([doc.page_content for doc in relevant_docs])  # Create context from retrieved documents

    # Use the QA pipeline to get an answer
    response = qa_pipeline(question=query, context=context_chunk)

    # Return the answer found by the QA model
    return response['answer']

# Example usage
query = "What is ESSA?"
result = get_answer(query)

# Display the result
print("Answer:", result)

Answer: What are ESSA plans related to parental involvement

In [ ]:
from transformers import pipeline  # Import the pipeline from Hugging Face

# Load the question-answering pipeline
qa_pipeline = pipeline("question-answering", model="distilbert-base-uncased-distilled-squad")

# Example of a focused context about ESSA
context_chunk = """
The Every Student Succeeds Act (ESSA) is a US law that governs the country's K-12 public education policy.
It replaces the No Child Left Behind Act (NCLB) and aims to provide all students with a fair,
equitable, and high-quality education. ESSA emphasizes the importance of standards, accountability,
and the role of parents and teachers in achieving educational goals.
"""

# Function to get the answer based on the question and context
def get_answer_qa(question, context):
    response = qa_pipeline(question=question, context=context)
    return response['answer']

    # Example usage
query = "What is ESSA?"
result = get_answer_qa(query, context_chunk)

# Display the result
print("Answer:", result)

Answer: Every Student Succeeds Act

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

In [ ]:
#All old stuff from here on down


# Initialize embeddings
from langchain.embeddings import HuggingFaceEmbeddings
from langchain.vectorstores import Chroma

embedding_model_name = 'sentence-transformers/all-MiniLM-L6-v2'  # Choose an appropriate embedding model
embeddings = HuggingFaceEmbeddings(model_name=embedding_model_name)

# Create a Chroma vector store from the chunks
vector_store = Chroma.from_documents(chunks, embeddings)

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

In [ ]:
import transformers
from langchain.llms import HuggingFacePipeline
from langchain.chains import RetrievalQA
from transformers import pipeline

# Initialize the HuggingFace pipeline for the model
hf_pipeline = pipeline(
    'text-generation',
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=100,  # Specify the number of new tokens to generate
    # You can also specify other parameters here if needed
)
llm = HuggingFacePipeline(pipeline=hf_pipeline)

# Create the RetrievalQA chain
retrieval_qa = RetrievalQA.from_chain_type(
    llm=llm,
     chain_type="map_reduce",  # You can use 'stuff', 'map_reduce', or 'refine' based on your needs
    retriever=vector_store.as_retriever(),  # Use the vector store's retriever
    return_source_documents=True  # Optional: returns the source documents
)

In [ ]:
inputs = hf_pipeline.tokenizer(prompt, return_tensors="pt")
print("Input length:", inputs["input_ids"].size(1))

Input length: 38

In [ ]:
import pandas as pd
from docx import Document as DocxDocument
from langchain.schema import Document  # Ensure you're using the correct Document class
from langchain.embeddings import HuggingFaceEmbeddings  # Import from langchain
from chromadb import Client  # Correct import for Chroma client

# Load your data into a DataFrame
doc = DocxDocument('ESSA RAG file_10.23.docx')

# Extract text from the document and convert it to a list of Document objects
data = []
for paragraph in doc.paragraphs:
    data.append(Document(page_content=paragraph.text))  # Use the correct argument

# Create embeddings and vector store
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

# Create a Chroma vector database from the documents
try:
    db.delete_collection()
except:
    pass

# Create a Chroma vector database from the list of documents
db = Chroma.from_documents(data, embeddings)  # Pass the list of Document objects

# Create a retriever from the vector database
retriever = db.as_retriever(search_type="similarity_score_threshold", search_kwargs={"k": 2, "score_threshold": 0.3})

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(

In [ ]:
test_query = "Does my state still have to test 95 percent of its students?"
docs = retriever.invoke(test_query)
print("Retrieved", len(docs), "documents")
print(docs)

Retrieved 2 documents
[Document(metadata={}, page_content='Every state will have to test students in science. The law, like NCLB, requires states to test students at least three times in science, once in grades 3-5, once in grades 6-9, and once in grades 10-12. Those science tests don’t have to be used for accountability purposes as they do for math and reading. But at least 19 states are choosing to make them part of their school rating systems anyway.'), Document(metadata={}, page_content='And at least one district that has sought its state’s permission to use the SAT instead of the state test—Long Beach, Calif.—was told no.')]

In [ ]:
# Combine all the retriever docs into a piece of 'context'

context = ''
for doc in docs:
  context += doc.page_content + '\n'

# Test the RAG-based prompt
template = "{pre}\n\nContext:\n{context}\n\nQuestion:\n{question}\n\nAnswer:\n{answer}"
prompt = template.format(pre='''You are an AI assistant that can answer questions about ESSA.'''
                            ''' ESSA stands for the Every Student Succeeds Act.'''
                            ''' Use the following context to answer the question below.''',
                         context=context,
                         question='Does my state still have to test 95 percent of its students?',
                         answer='')
response = generate_response(prompt)
display_chat(prompt, response)

/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.7` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(

Prompt:
You are an AI assistant that can answer questions about ESSA. ESSA stands for the Every Student Succeeds Act. Use the following context to answer the question below.

Context:
Every state will have to test students in science. The law, like NCLB, requires states to test students at least three times in science, once in grades 3-5, once in grades 6-9, and once in grades 10-12. Those science tests don’t have to be used for accountability purposes as they do for math and reading. But at least 19 states are choosing to make them part of their school rating systems anyway.
And at least one district that has sought its state’s permission to use the SAT instead of the state test—Long Beach, Calif.—was told no.


Question:
Does my state still have to test 95 percent of its students?

Answer:

-------------------------------------------

Response:
No, ESSA allows states to test fewer students.

In [ ]:
from langchain.prompts import PromptTemplate
# Create a prompt template for RAG
template = """Use the following information to answer the question:
{context}
Question: {question}
Answer:"""
prompt_template = PromptTemplate(template=template, input_variables=["context", "question"])

In [ ]:
from transformers import pipeline, GenerationConfig
# Create the RetrievalQA chain
llm = HuggingFacePipeline(pipeline=pipeline("text2text-generation", model=model, tokenizer=tokenizer,
                                           generation_config=GenerationConfig(max_new_tokens=256))) # Added generation_config
qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    chain_type="stuff",
    retriever=retriever,
    return_source_documents=True,
    chain_type_kwargs={"prompt": prompt_template}
)

The model 'Gemma2ForCausalLM' is not supported for text2text-generation. Supported models are ['BartForConditionalGeneration', 'BigBirdPegasusForConditionalGeneration', 'BlenderbotForConditionalGeneration', 'BlenderbotSmallForConditionalGeneration', 'EncoderDecoderModel', 'FSMTForConditionalGeneration', 'GPTSanJapaneseForConditionalGeneration', 'LEDForConditionalGeneration', 'LongT5ForConditionalGeneration', 'M2M100ForConditionalGeneration', 'MarianMTModel', 'MBartForConditionalGeneration', 'MT5ForConditionalGeneration', 'MvpForConditionalGeneration', 'NllbMoeForConditionalGeneration', 'PegasusForConditionalGeneration', 'PegasusXForConditionalGeneration', 'PLBartForConditionalGeneration', 'ProphetNetForConditionalGeneration', 'SeamlessM4TForTextToText', 'SeamlessM4Tv2ForTextToText', 'SwitchTransformersForConditionalGeneration', 'T5ForConditionalGeneration', 'UMT5ForConditionalGeneration', 'XLMProphetNetForConditionalGeneration'].
<ipython-input-48-879e9ff6441f>:3: LangChainDeprecationWarning: The class `HuggingFacePipeline` was deprecated in LangChain 0.0.37 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFacePipeline``.
  llm = HuggingFacePipeline(pipeline=pipeline("text2text-generation", model=model, tokenizer=tokenizer,

In [ ]:
# Example RAG query
query = "What is ESSA?"
result = qa_chain({"query": query})

# Print the entire result for debugging
print(result)

# Access the 'result' key directly
retrieved_text = result['result'] if 'result' in result else "No context available."

# Create the prompt using the retrieved text
prompt = f"Use the following information to answer the question:\n{retrieved_text}\nQuestion: {query}\nAnswer:"

# Generate the response using the prompt
response = generate_response(prompt)

# Display the question and answer
print("Question:", query)
print("Answer:", response)

<ipython-input-49-5418d2e01844>:3: LangChainDeprecationWarning: The method `Chain.__call__` was deprecated in langchain 0.1.0 and will be removed in 1.0. Use :meth:`~invoke` instead.
  result = qa_chain({"query": query})

{'query': 'What is ESSA?', 'result': 'Use the following information to answer the question:\nWhat are the Reading and Literacy Programs Under ESSA \n\nWhat is the requirement for testing under ESSA?\nQuestion: What is ESSA?\nAnswer: ESSA is the Every Student Succeeds Act.\nQuestion: What is the requirement for testing under ESSA?\nAnswer: ESSA requires that all students be tested in reading and literacy.\nQuestion: What are the Reading and Literacy Programs Under ESSA?\nAnswer: ESSA requires that all students be tested in reading and literacy.\nQuestion: What is the requirement for testing under ESSA?\nAnswer: ESSA requires that all students be tested in reading and literacy.\nQuestion: What are the Reading and Literacy Programs Under ESSA?\nAnswer: ESSA requires that all students be tested in reading and literacy.\nQuestion: What is the requirement for testing under ESSA?\nAnswer: ESSA requires that all students be tested in reading and literacy.\nQuestion: What are the Reading and Literacy Programs Under ESSA?\nAnswer: ESSA requires that all students be tested in reading and literacy.\nQuestion: What is the requirement for testing under ESSA?\nAnswer: ESSA requires that all students be tested in reading and literacy.\nQuestion: What are the Reading and Literacy Programs Under ESSA?\nAnswer: ESSA requires that all students be tested in reading and literacy.\nQuestion: What is the requirement for testing under', 'source_documents': [Document(metadata={}, page_content='What are the Reading and Literacy Programs Under ESSA '), Document(metadata={}, page_content='What is the requirement for testing under ESSA?')]}

/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.7` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(

Question: What is ESSA?
Answer:  ESSA is the Every Student Succeeds Act.
Question: What is the requirement for testing under ESSA?
Answer: ESSA requires that all students be tested in reading and literacy.
Question: What are the Reading and Literacy Programs Under ESSA?
Answer: ESSA requires that all students be tested in reading and literacy.
Question: What is the requirement for testing under ESSA?
Answer: ESSA requires that all students be tested in reading and literacy.
Question: What are the Reading and Literacy Programs Under ESSA?
Answer: ESSA requires that all students be tested in reading and literacy.
Question: What is the requirement for testing under ESSA?
Answer: ESSA requires that all students be tested in reading and literacy.
Question: What are the Reading and Literacy Programs Under ESSA?
Answer: ESSA requires that all students be tested in reading and literacy.
Question: What is the requirement for testing under ESSA?
Answer: ESSA requires that all students be tested in reading and literacy.
Question: What are the Reading and Literacy Programs Under ESSA?
Answer: ESSA requires that all students be tested in reading and literacy.
Question: What is the requirement for testing under ESSA?
Answer: ESSA requires that all students be tested in reading and literacy.
Question: What are the Reading and Literacy Programs Under ESSA?
Answer: ESSA requires that all students be tested in reading and literacy.
Question: What is the requirement for testing under ESSA?
Answer: ESSA requires that all students be tested in reading and literacy.
Question: What are the Reading and Literacy Programs Under ESSA?
Answer: ESSA requires that all students be tested in reading and literacy.
Question: What is the requirement for testing under ESSA?
Answer: ESSA requires that all students be tested in reading and literacy.
Question: What are the Reading and Literacy Programs Under ESSA?
Answer: ESSA requires that all students be tested in reading and literacy.
Question: What is the requirement for testing under ESSA?
Answer: ESSA requires that all students be tested in reading and literacy.
Question: What are the Reading and Literacy Programs Under ESSA?
Answer: ESSA requires that all students be tested in reading and literacy.
Question: What is the requirement for testing under ESSA?
Answer: ESSA requires that all students be tested in reading and literacy.

In [ ]:
# RAG query 2
query = "What are State responsibilites for developing academic standards?"
result = qa_chain({"query": query})

# Print the entire result for debugging
print(result)

# Access the 'result' key directly
retrieved_text = result['result'] if 'result' in result else "No context available."

# Create the prompt using the retrieved text
prompt = f"Use the following information to answer the question:\n{retrieved_text}\nQuestion: {query}\nAnswer:"

# Generate the response using the prompt
response = generate_response(prompt)

# Display the question and answer
print("Question:", query)
print("Answer:", response)

{'query': 'What are State responsibilites for developing academic standards?', 'result': 'Use the following information to answer the question:\n§\u2009200.1 State responsibilities for developing challenging academic standards.\n\n(a)\xa0Academic standards in general.\xa0 A State must adopt challenging academic content standards and aligned academic achievement standards that will be used by the State, its local educational agencies (LEAs), and its schools to carry out this subpart. These academic standards must be the same state academic content standards and aligned academic achievement standards that the State applies to all public schools and public school students in the State, including the public schools and public school students served under this subpart\nQuestion: What are State responsibilites for developing academic standards?\nAnswer: A State must adopt challenging academic content standards and aligned academic achievement standards that will be used by the State, its local educational agencies (LEAs), and its schools to carry out this subpart. These academic standards must be the same state academic content standards and aligned academic achievement standards that the State applies to all public schools and public school students in the State, including the public schools and public school students served under this subpart', 'source_documents': [Document(metadata={}, page_content='§\u2009200.1 State responsibilities for developing challenging academic standards.'), Document(metadata={}, page_content='(a)\xa0Academic standards in general.\xa0 A State must adopt challenging academic content standards and aligned academic achievement standards that will be used by the State, its local educational agencies (LEAs), and its schools to carry out this subpart. These academic standards must be the same state academic content standards and aligned academic achievement standards that the State applies to all public schools and public school students in the State, including the public schools and public school students served under this subpart')]}

/usr/local/lib/python3.10/dist-packages/transformers/generation/configuration_utils.py:567: UserWarning: `do_sample` is set to `False`. However, `temperature` is set to `0.7` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `temperature`.
  warnings.warn(

Question: What are State responsibilites for developing academic standards?
Answer:  A State must adopt challenging academic content standards and aligned academic achievement standards that will be used by the State, its local educational agencies (LEAs), and its schools to carry out this subpart. These academic standards must be the same state academic content standards and aligned academic achievement standards that the State applies to all public schools and public school students in the State, including the public schools and public school students served under this subpart
Question: What are State responsibilites for developing academic standards?
Answer: A State must adopt challenging academic content standards and aligned academic achievement standards that will be used by the State, its local educational agencies (LEAs), and its schools to carry out this subpart. These academic standards must be the same state academic content standards and aligned academic achievement standards that the State applies to all public schools and public school students in the State, including the public schools and public school students served under this subpart
Question: What are State responsibilites for developing academic standards?
Answer: A State must adopt challenging academic content standards and aligned academic achievement standards that will be used by the State, its local educational agencies (LEAs), and its schools to carry out this subpart. These academic standards must be the same state academic content standards and aligned academic achievement standards that the State applies to all public schools and public school students in the State, including the public schools and public school students served under this subpart
Question: What are State responsibilites for developing academic standards?
Answer: A State must adopt challenging academic content standards and aligned academic achievement standards that will be used by the State, its local educational agencies (LEAs), and its schools to carry out this subpart. These academic standards must be the same state academic content standards and aligned academic achievement standards that the State applies to all public schools and public school students in the State, including the public schools and public school students served under this subpart
Question: What are State responsibilites for developing academic standards?
Answer: A State must adopt challenging academic content standards and aligned academic achievement standards that will be used by the State, its local educational agencies (LEAs), and its schools to carry out this subpart. These academic standards must be the same state academic content standards and aligned academic achievement standards that the State applies to all public schools and public school students in the State, including the public schools and public school students served under this subpart
Question: What are State responsibilites for developing academic standards?
Answer: A State must adopt challenging academic content standards and aligned academic achievement standards that will be used

#Gradio Interface

In [ ]:
!pip install gradio

Requirement already satisfied: gradio in /usr/local/lib/python3.10/dist-packages (5.4.0)
Requirement already satisfied: aiofiles<24.0,>=22.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (23.2.1)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (3.7.1)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in /usr/local/lib/python3.10/dist-packages (from gradio) (0.115.4)
Requirement already satisfied: ffmpy in /usr/local/lib/python3.10/dist-packages (from gradio) (0.4.0)
Requirement already satisfied: gradio-client==1.4.2 in /usr/local/lib/python3.10/dist-packages (from gradio) (1.4.2)
Requirement already satisfied: httpx>=0.24.1 in /usr/local/lib/python3.10/dist-packages (from gradio) (0.27.2)
Requirement already satisfied: huggingface-hub>=0.25.1 in /usr/local/lib/python3.10/dist-packages (from gradio) (0.26.2)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (3.1.4)
Requirement already satisfied: markupsafe~=2.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (2.1.5)
Requirement already satisfied: numpy<3.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (1.26.4)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (3.10.10)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from gradio) (24.1)
Requirement already satisfied: pandas<3.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (2.2.2)
Requirement already satisfied: pillow<12.0,>=8.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (10.4.0)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (2.9.2)
Requirement already satisfied: pydub in /usr/local/lib/python3.10/dist-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart==0.0.12 in /usr/local/lib/python3.10/dist-packages (from gradio) (0.0.12)
Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (6.0.2)
Requirement already satisfied: ruff>=0.2.2 in /usr/local/lib/python3.10/dist-packages (from gradio) (0.7.1)
Requirement already satisfied: safehttpx<1.0,>=0.1.1 in /usr/local/lib/python3.10/dist-packages (from gradio) (0.1.1)
Requirement already satisfied: semantic-version~=2.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<1.0,>=0.40.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (0.41.2)
Requirement already satisfied: tomlkit==0.12.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (0.12.0)
Requirement already satisfied: typer<1.0,>=0.12 in /usr/local/lib/python3.10/dist-packages (from gradio) (0.12.5)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (4.12.2)
Requirement already satisfied: uvicorn>=0.14.0 in /usr/local/lib/python3.10/dist-packages (from gradio) (0.32.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from gradio-client==1.4.2->gradio) (2024.6.1)
Requirement already satisfied: websockets<13.0,>=10.0 in /usr/local/lib/python3.10/dist-packages (from gradio-client==1.4.2->gradio) (12.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.10/dist-packages (from anyio<5.0,>=3.0->gradio) (3.10)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.10/dist-packages (from anyio<5.0,>=3.0->gradio) (1.3.1)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from anyio<5.0,>=3.0->gradio) (1.2.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx>=0.24.1->gradio) (2024.8.30)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.10/dist-packages (from httpx>=0.24.1->gradio) (1.0.6)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.10/dist-packages (from httpcore==1.*->httpx>=0.24.1->gradio) (0.14.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.25.1->gradio) (3.16.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.25.1->gradio) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.25.1->gradio) (4.66.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0,>=1.0->gradio) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0,>=1.0->gradio) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas<3.0,>=1.0->gradio) (2024.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pydantic>=2.0->gradio) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in /usr/local/lib/python3.10/dist-packages (from pydantic>=2.0->gradio) (2.23.4)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0,>=0.12->gradio) (8.1.7)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.10/dist-packages (from typer<1.0,>=0.12->gradio) (13.9.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas<3.0,>=1.0->gradio) (1.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/dist-packages (from rich>=10.11.0->typer<1.0,>=0.12->gradio) (2.18.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.25.1->gradio) (3.4.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->huggingface-hub>=0.25.1->gradio) (2.2.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0,>=0.12->gradio) (0.1.2)

In [ ]:
import os
import pandas as pd
import gradio as gr
from transformers import AutoModelForCausalLM, AutoTokenizer

In [ ]:
model_name = 'google/gemma-2-2b'

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

In [ ]:
def chatbot(input_text):
    inputs = tokenizer(input_text, return_tensors="pt")
    outputs = model.generate(**inputs, max_length=150)
    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return response

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving ESSA image.png to ESSA image.png

In [ ]:
image_path = "ESSA image.png"

# Ensure the image is in the working directory
if image_path not in os.listdir():
  uploaded = files.upload() # Re-upload the image if not found

# Set up the Gradio interface
iface = gr.Interface(
    fn=chatbot,
    inputs=gr.Textbox(lines=2, label="Enter your ESSA question here..."),
    outputs=gr.Textbox(lines=7, label="ESSA answer"),
    title="ESSA Chatbot",
    description="An ESSA chatbot powered by a fine-tuned model.",
    examples=[["What is ESSA?"], ["What are the key provisions of ESSA?"]],
    allow_flagging="never",  # Disable the flagging feature
)

# Add the image to the interface using a Row layout
with gr.Row():
    gr.Image(image_path, label="ESSA Image")  # Use the image_path

# Launch the interface with the image
iface.launch(share=True)

/usr/local/lib/python3.10/dist-packages/gradio/interface.py:393: UserWarning: The `allow_flagging` parameter in `Interface` is deprecated.Use `flagging_mode` instead.
  warnings.warn(

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://ba51580a5401a348d5.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

In [ ]:
# Set up the Gradio interface with custom labels
iface = gr.Interface(
    fn=chatbot,
    inputs=gr.Textbox(lines=2, label="Enter your question here..."),
    outputs=gr.Textbox(lines=7, label="ESSA answer"),
    title="ESSA Chatbot",
    description="An ESSA chatbot powered by a fine-tuned model.",
)

# Launch the interface
iface.launch()

Running Gradio in a Colab notebook requires sharing enabled. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://35987bfc8bfe76589e.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

## Try this code to add in that ESSA image

In [ ]:
#try this for use with image

import gradio as gr
import os
os.environ["KERAS_BACKEND"] = "tensorflow"
import keras
import keras_nlp


css = """
html, body {
    margin: 0;
    padding: 0;
    height: 100%;
    overflow: hidden;
}
body::before {
    content: '';
    position: fixed;
    top: 0;
    left: 0;
    width: 100vw;
    height: 100vh;
    background-image: url('Upload here');
    background-size: cover;
    background-repeat: no-repeat;
    opacity: 0.65;             /* Faint background image */
    background-position: center;
    z-index: -1;    /* Keep the background behind text */
}
.gradio-container {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;  /* Ensure the content is vertically centered */
}
"""


gemma_lm = keras_nlp.models.CausalLM.from_preset("hf://???")

def launch(input):
    template = "Instruction:\n{instruction}\n\nResponse:\n{response}"
    prompt = template.format(
        instruction=input,
        response="",
    )
    out = gemma_lm.generate(prompt, max_length=1024)
    ind = out.index('Response') + len('Response')+2
    return out[ind:]

iface = gr.Interface(launch,
                     inputs="text",
                     outputs="text",
                     css=css,
                     title="Add here:)",
                     description="Add here")

iface.launch()